-- ============================================================
-- Kategori ağacı: 19 kök, 143 alt kategori
--
-- Önceki ağaçta 12 kökün 5'i tamamen boştu; alıcı "Kimya" ya da "Yapı"
-- seçtiğinde hiçbir daralma yapamıyordu. B2B'de kategori, aramanın
-- kendisidir: yeterince derin değilse alıcı serbest metne düşer ve
-- yanlış tedarikçiye ulaşır.
--
-- MEVCUT SATIRLAR KORUNUR. Aynı kavramı anlatan kategoriler yeniden
-- ADLANDIRILIR (slug'ları üzerinden eşleşerek), yenileri eklenir.
-- Böylece hâlihazırda o kategoriye bağlı ürünler yerinde kalır.
-- ============================================================

-- ---------- Kök kategoriler ----------
insert into categories (slug, name, parent_id, sort_order) values
  ('ambalaj', 'Ambalaj', null, 10),
  ('tekstil', 'Tekstil ve Hazır Giyim', null, 20),
  ('gida', 'Gıda ve İçecek', null, 30),
  ('yapi', 'Yapı ve İnşaat', null, 40),
  ('makine', 'Makine ve Ekipman', null, 50),
  ('kimya', 'Kimya ve Petrokimya', null, 60),
  ('plastik', 'Plastik ve Kauçuk', null, 70),
  ('metal-madencilik', 'Metal ve Madencilik', null, 80),
  ('elektronik', 'Elektrik ve Elektronik', null, 90),
  ('otomotiv', 'Otomotiv ve Yedek Parça', null, 100),
  ('mobilya-ev-yasam', 'Mobilya ve Ev Yaşam', null, 110),
  ('kozmetik', 'Kozmetik ve Kişisel Bakım', null, 120),
  ('temizlik-hijyen', 'Temizlik ve Hijyen', null, 130),
  ('medikal-saglik', 'Medikal ve Sağlık', null, 140),
  ('tarim-hayvancilik', 'Tarım ve Hayvancılık', null, 150),
  ('hirdavat', 'Hırdavat ve El Aletleri', null, 160),
  ('kirtasiye', 'Kırtasiye ve Ofis', null, 170),
  ('oyuncak-hobi-spor', 'Oyuncak, Hobi ve Spor', null, 180),
  ('lojistik-depolama', 'Lojistik ve Depolama', null, 190)
on conflict (slug) do update set
  name = excluded.name,
  parent_id = null,
  sort_order = excluded.sort_order;

-- ---------- Alt kategoriler ----------
insert into categories (slug, name, parent_id, sort_order)
select v.slug, v.name, p.id, v.sort_order
from (values
  ('karton-kutu', 'Karton Kutu ve Koli', 'ambalaj', 10),
  ('oluklu-mukavva', 'Oluklu Mukavva', 'ambalaj', 20),
  ('plastik-ambalaj', 'Plastik Ambalaj', 'ambalaj', 30),
  ('cam-ambalaj', 'Cam Ambalaj', 'ambalaj', 40),
  ('metal-ambalaj', 'Metal Ambalaj ve Teneke', 'ambalaj', 50),
  ('esnek-ambalaj', 'Esnek Ambalaj ve Film', 'ambalaj', 60),
  ('etiket-baski', 'Etiket ve Baskı', 'ambalaj', 70),
  ('koli-bandi', 'Koli Bandı ve Streç', 'ambalaj', 80),
  ('palet-tasima-kabi', 'Palet ve Taşıma Kabı', 'ambalaj', 90),
  ('kozmetik-ilac-ambalaji', 'Kozmetik ve İlaç Ambalajı', 'ambalaj', 100),
  ('kumas', 'Kumaş', 'tekstil', 10),
  ('iplik', 'İplik ve Elyaf', 'tekstil', 20),
  ('orme-giyim', 'Örme Giyim', 'tekstil', 30),
  ('dokuma-giyim', 'Dokuma Giyim', 'tekstil', 40),
  ('is-elbisesi-uniforma', 'İş Elbisesi ve Üniforma', 'tekstil', 50),
  ('ev-tekstili', 'Ev Tekstili', 'tekstil', 60),
  ('havlu-bornoz', 'Havlu ve Bornoz', 'tekstil', 70),
  ('corap', 'Çorap', 'tekstil', 80),
  ('deri-ayakkabi', 'Deri ve Ayakkabı', 'tekstil', 90),
  ('teknik-tekstil', 'Teknik Tekstil', 'tekstil', 100),
  ('aksesuar-tuhafiye', 'Aksesuar ve Tuhafiye', 'tekstil', 110),
  ('kuru-gida', 'Kuru Gıda ve Bakliyat', 'gida', 10),
  ('kuruyemis-kuru-meyve', 'Kuruyemiş ve Kuru Meyve', 'gida', 20),
  ('un-unlu-mamul', 'Un ve Unlu Mamul', 'gida', 30),
  ('yag-zeytinyagi', 'Yağ ve Zeytinyağı', 'gida', 40),
  ('sut-urunleri', 'Süt ve Süt Ürünleri', 'gida', 50),
  ('et-urunleri', 'Et ve Et Ürünleri', 'gida', 60),
  ('su-urunleri', 'Su Ürünleri', 'gida', 70),
  ('taze-meyve-sebze', 'Taze Meyve Sebze', 'gida', 80),
  ('dondurulmus-gida', 'Dondurulmuş Gıda', 'gida', 90),
  ('sekerleme-cikolata', 'Şekerleme ve Çikolata', 'gida', 100),
  ('icecek', 'İçecek', 'gida', 110),
  ('baharat-cesni', 'Baharat ve Çeşni', 'gida', 120),
  ('gida-katki', 'Gıda Katkı Maddeleri', 'gida', 130),
  ('cimento-beton', 'Çimento ve Beton', 'yapi', 10),
  ('seramik-karo', 'Seramik ve Karo', 'yapi', 20),
  ('dogal-tas-mermer', 'Doğal Taş ve Mermer', 'yapi', 30),
  ('yalitim', 'Yalıtım Malzemeleri', 'yapi', 40),
  ('boya-vernik', 'Boya ve Vernik', 'yapi', 50),
  ('kapi-pencere', 'Kapı ve Pencere', 'yapi', 60),
  ('tesisat-boru', 'Tesisat ve Boru', 'yapi', 70),
  ('yapi-kimyasallari', 'Yapı Kimyasalları', 'yapi', 80),
  ('cati-cephe', 'Çatı ve Cephe', 'yapi', 90),
  ('zemin-kaplama', 'Zemin Kaplama', 'yapi', 100),
  ('prefabrik-konteyner', 'Prefabrik ve Konteyner Yapı', 'yapi', 110),
  ('gida-isleme-makineleri', 'Gıda İşleme Makineleri', 'makine', 10),
  ('tekstil-makineleri', 'Tekstil Makineleri', 'makine', 20),
  ('ambalaj-makineleri', 'Ambalaj Makineleri', 'makine', 30),
  ('plastik-makineleri', 'Plastik İşleme Makineleri', 'makine', 40),
  ('cnc-tezgah', 'Metal İşleme ve CNC', 'makine', 50),
  ('tarim-makineleri', 'Tarım Makineleri', 'makine', 60),
  ('is-makineleri', 'İş Makineleri', 'makine', 70),
  ('kompresor-pompa', 'Kompresör ve Pompa', 'makine', 80),
  ('jenerator-enerji', 'Jeneratör ve Enerji', 'makine', 90),
  ('yedek-parca-rulman', 'Yedek Parça ve Rulman', 'makine', 100),
  ('endustriyel-kimyasallar', 'Endüstriyel Kimyasallar', 'kimya', 10),
  ('polimer-recine', 'Polimer ve Reçine', 'kimya', 20),
  ('pigment-boyarmadde', 'Boya Hammaddesi ve Pigment', 'kimya', 30),
  ('yapistirici', 'Yapıştırıcı ve Kimyasal', 'kimya', 40),
  ('temizlik-kimyasallari', 'Temizlik Kimyasalları', 'kimya', 50),
  ('gubre-tarim-kimyasi', 'Gübre ve Tarım Kimyası', 'kimya', 60),
  ('laboratuvar-kimyasallari', 'Laboratuvar Kimyasalları', 'kimya', 70),
  ('madeni-yag', 'Yağlar ve Madeni Yağ', 'kimya', 80),
  ('plastik-hammadde', 'Plastik Hammadde', 'plastik', 10),
  ('enjeksiyon-urunleri', 'Enjeksiyon Ürünleri', 'plastik', 20),
  ('plastik-kasa-bidon', 'Plastik Kasa ve Bidon', 'plastik', 30),
  ('plastik-boru-profil', 'Boru ve Profil', 'plastik', 40),
  ('kaucuk-conta', 'Kauçuk ve Conta', 'plastik', 50),
  ('levha-film', 'Levha ve Film', 'plastik', 60),
  ('demir-celik', 'Demir ve Çelik', 'metal-madencilik', 10),
  ('paslanmaz-celik', 'Paslanmaz Çelik', 'metal-madencilik', 20),
  ('aluminyum', 'Alüminyum', 'metal-madencilik', 30),
  ('bakir-pirinc', 'Bakır ve Pirinç', 'metal-madencilik', 40),
  ('sac-profil', 'Sac ve Profil', 'metal-madencilik', 50),
  ('dokum-talasli-imalat', 'Döküm ve Talaşlı İmalat', 'metal-madencilik', 60),
  ('maden-cevher', 'Maden ve Cevher', 'metal-madencilik', 70),
  ('hurda-geri-donusum', 'Hurda ve Geri Dönüşüm', 'metal-madencilik', 80),
  ('kablo-konnektor', 'Kablo ve İletken', 'elektronik', 10),
  ('aydinlatma', 'Aydınlatma ve LED', 'elektronik', 20),
  ('pano-salt', 'Elektrik Panosu ve Şalt', 'elektronik', 30),
  ('elektronik-modul', 'Elektronik Bileşen', 'elektronik', 40),
  ('gunes-enerjisi-panel', 'Güneş Enerjisi ve Panel', 'elektronik', 50),
  ('batarya-enerji-depolama', 'Batarya ve Enerji Depolama', 'elektronik', 60),
  ('beyaz-esya-kucuk-ev', 'Beyaz Eşya ve Küçük Ev Aleti', 'elektronik', 70),
  ('bilisim-donanimi', 'Bilişim Donanımı', 'elektronik', 80),
  ('motor-sanziman', 'Motor ve Şanzıman Parçaları', 'otomotiv', 10),
  ('fren-suspansiyon', 'Fren ve Süspansiyon', 'otomotiv', 20),
  ('kaporta-aksesuar', 'Kaporta ve Aksesuar', 'otomotiv', 30),
  ('lastik', 'Lastik ve Jant', 'otomotiv', 40),
  ('oto-elektrik', 'Oto Elektrik', 'otomotiv', 50),
  ('ticari-arac-romork', 'Ticari Araç ve Römork', 'otomotiv', 60),
  ('oto-kimyasallari', 'Oto Kimyasalları', 'otomotiv', 70),
  ('ofis-mobilyasi', 'Ofis Mobilyası', 'mobilya-ev-yasam', 10),
  ('ev-mobilyasi', 'Ev Mobilyası', 'mobilya-ev-yasam', 20),
  ('otel-kontrat-mobilya', 'Otel ve Kontrat Mobilya', 'mobilya-ev-yasam', 30),
  ('mutfak-banyo', 'Mutfak ve Banyo', 'mobilya-ev-yasam', 40),
  ('bahce-dis-mekan', 'Bahçe ve Dış Mekân', 'mobilya-ev-yasam', 50),
  ('ev-dekorasyon', 'Ev Dekorasyon', 'mobilya-ev-yasam', 60),
  ('mobilya-aksesuari', 'Mobilya Aksesuarı', 'mobilya-ev-yasam', 70),
  ('cilt-bakimi', 'Cilt Bakımı', 'kozmetik', 10),
  ('sac-bakimi', 'Saç Bakımı', 'kozmetik', 20),
  ('makyaj', 'Makyaj', 'kozmetik', 30),
  ('parfum-deodorant', 'Parfüm ve Deodorant', 'kozmetik', 40),
  ('sabun-dus', 'Sabun ve Duş Ürünleri', 'kozmetik', 50),
  ('bebek-bakim', 'Bebek Bakım', 'kozmetik', 60),
  ('ozel-uretim-private-label', 'Özel Üretim (Private Label)', 'kozmetik', 70),
  ('endustriyel-temizlik', 'Endüstriyel Temizlik', 'temizlik-hijyen', 10),
  ('kagit-urunleri', 'Kâğıt Ürünleri', 'temizlik-hijyen', 20),
  ('camasir-bulasik', 'Çamaşır ve Bulaşık', 'temizlik-hijyen', 30),
  ('dezenfektan', 'Dezenfektan', 'temizlik-hijyen', 40),
  ('temizlik-ekipmani', 'Temizlik Ekipmanı', 'temizlik-hijyen', 50),
  ('tibbi-sarf', 'Tıbbi Sarf Malzeme', 'medikal-saglik', 10),
  ('tibbi-cihaz', 'Tıbbi Cihaz', 'medikal-saglik', 20),
  ('kisisel-koruyucu-donanim', 'Kişisel Koruyucu Donanım', 'medikal-saglik', 30),
  ('laboratuvar-ekipmani', 'Laboratuvar Ekipmanı', 'medikal-saglik', 40),
  ('ilac-takviye', 'İlaç ve Takviye', 'medikal-saglik', 50),
  ('ortopedi-rehabilitasyon', 'Ortopedi ve Rehabilitasyon', 'medikal-saglik', 60),
  ('tohum-fide', 'Tohum ve Fide', 'tarim-hayvancilik', 10),
  ('sera-ekipman', 'Sera ve Ekipman', 'tarim-hayvancilik', 20),
  ('sulama-sistemleri', 'Sulama Sistemleri', 'tarim-hayvancilik', 30),
  ('yem-hayvan-besleme', 'Yem ve Hayvan Besleme', 'tarim-hayvancilik', 40),
  ('hayvancilik-ekipmani', 'Hayvancılık Ekipmanı', 'tarim-hayvancilik', 50),
  ('su-urunleri-yetistiriciligi', 'Su Ürünleri Yetiştiriciliği', 'tarim-hayvancilik', 60),
  ('el-aletleri', 'El Aletleri', 'hirdavat', 10),
  ('elektrikli-el-aleti', 'Elektrikli El Aleti', 'hirdavat', 20),
  ('baglanti-elemanlari', 'Bağlantı Elemanları', 'hirdavat', 30),
  ('kesici-takim', 'Kesici Takım', 'hirdavat', 40),
  ('kilit-mentese', 'Kilit ve Menteşe', 'hirdavat', 50),
  ('is-guvenligi-ekipmani', 'İş Güvenliği Ekipmanı', 'hirdavat', 60),
  ('kagit-defter', 'Kâğıt ve Defter', 'kirtasiye', 10),
  ('yazi-gerecleri', 'Yazı Gereçleri', 'kirtasiye', 20),
  ('ofis-sarf', 'Ofis Sarf Malzemesi', 'kirtasiye', 30),
  ('baski-toner', 'Baskı ve Toner', 'kirtasiye', 40),
  ('promosyon-urunleri', 'Promosyon Ürünleri', 'kirtasiye', 50),
  ('oyuncak', 'Oyuncak', 'oyuncak-hobi-spor', 10),
  ('spor-malzemesi', 'Spor Malzemesi', 'oyuncak-hobi-spor', 20),
  ('kamp-outdoor', 'Kamp ve Outdoor', 'oyuncak-hobi-spor', 30),
  ('hobi-el-sanatlari', 'Hobi ve El Sanatları', 'oyuncak-hobi-spor', 40),
  ('parti-hediyelik', 'Parti ve Hediyelik', 'oyuncak-hobi-spor', 50),
  ('raf-depo-sistemleri', 'Raf ve Depo Sistemleri', 'lojistik-depolama', 10),
  ('istif-tasima-ekipmani', 'İstif ve Taşıma Ekipmanı', 'lojistik-depolama', 20),
  ('soguk-zincir-ekipmani', 'Soğuk Zincir Ekipmanı', 'lojistik-depolama', 30),
  ('konteyner-tasima-kabi', 'Konteyner ve Taşıma Kabı', 'lojistik-depolama', 40)
) as v(slug, name, parent_slug, sort_order)
join categories p on p.slug = v.parent_slug
on conflict (slug) do update set
  name = excluded.name,
  parent_id = excluded.parent_id,
  sort_order = excluded.sort_order;

-- ---------- Çeviriler ----------
-- Her dil kendi slug'ını taşır: /tr/kategori/ambalaj, /en/category/packaging.
insert into category_translations (category_id, locale, name, slug)
select c.id, v.locale, v.name, v.slug
from (values
  ('ambalaj', 'tr', 'Ambalaj', 'ambalaj'),
  ('ambalaj', 'en', 'Packaging', 'packaging'),
  ('ambalaj', 'ru', 'Упаковка', 'upakovka'),
  ('karton-kutu', 'tr', 'Karton Kutu ve Koli', 'karton-kutu-koli'),
  ('karton-kutu', 'en', 'Cardboard Boxes', 'cardboard-boxes'),
  ('karton-kutu', 'ru', 'Картонные коробки', 'kartonnye-korobki'),
  ('oluklu-mukavva', 'tr', 'Oluklu Mukavva', 'oluklu-mukavva'),
  ('oluklu-mukavva', 'en', 'Corrugated Board', 'corrugated-board'),
  ('oluklu-mukavva', 'ru', 'Гофрокартон', 'gofrokarton'),
  ('plastik-ambalaj', 'tr', 'Plastik Ambalaj', 'plastik-ambalaj'),
  ('plastik-ambalaj', 'en', 'Plastic Packaging', 'plastic-packaging'),
  ('plastik-ambalaj', 'ru', 'Пластиковая упаковка', 'plastikovaya-upakovka'),
  ('cam-ambalaj', 'tr', 'Cam Ambalaj', 'cam-ambalaj'),
  ('cam-ambalaj', 'en', 'Glass Packaging', 'glass-packaging'),
  ('cam-ambalaj', 'ru', 'Стеклянная тара', 'steklyannaya-tara'),
  ('metal-ambalaj', 'tr', 'Metal Ambalaj ve Teneke', 'metal-ambalaj'),
  ('metal-ambalaj', 'en', 'Metal Cans', 'metal-cans'),
  ('metal-ambalaj', 'ru', 'Металлическая тара', 'metallicheskaya-tara'),
  ('esnek-ambalaj', 'tr', 'Esnek Ambalaj ve Film', 'esnek-ambalaj'),
  ('esnek-ambalaj', 'en', 'Flexible Packaging', 'flexible-packaging'),
  ('esnek-ambalaj', 'ru', 'Гибкая упаковка', 'gibkaya-upakovka'),
  ('etiket-baski', 'tr', 'Etiket ve Baskı', 'etiket-baski'),
  ('etiket-baski', 'en', 'Labels and Printing', 'labels-printing'),
  ('etiket-baski', 'ru', 'Этикетки и печать', 'etiketki-pechat'),
  ('koli-bandi', 'tr', 'Koli Bandı ve Streç', 'koli-bandi-strec'),
  ('koli-bandi', 'en', 'Tape and Stretch Film', 'tape-stretch-film'),
  ('koli-bandi', 'ru', 'Скотч и стрейч', 'skotch-streych'),
  ('palet-tasima-kabi', 'tr', 'Palet ve Taşıma Kabı', 'palet-tasima-kabi'),
  ('palet-tasima-kabi', 'en', 'Pallets and Crates', 'pallets-crates'),
  ('palet-tasima-kabi', 'ru', 'Паллеты и ящики', 'pallety-yashchiki'),
  ('kozmetik-ilac-ambalaji', 'tr', 'Kozmetik ve İlaç Ambalajı', 'kozmetik-ilac-ambalaji'),
  ('kozmetik-ilac-ambalaji', 'en', 'Cosmetic and Pharma Packaging', 'cosmetic-pharma-packaging'),
  ('kozmetik-ilac-ambalaji', 'ru', 'Упаковка для косметики и фармы', 'upakovka-kosmetika-farma'),
  ('tekstil', 'tr', 'Tekstil ve Hazır Giyim', 'tekstil-hazir-giyim'),
  ('tekstil', 'en', 'Textile and Apparel', 'textile-apparel'),
  ('tekstil', 'ru', 'Текстиль и одежда', 'tekstil-odezhda'),
  ('kumas', 'tr', 'Kumaş', 'kumas'),
  ('kumas', 'en', 'Fabrics', 'fabrics'),
  ('kumas', 'ru', 'Ткани', 'tkani'),
  ('iplik', 'tr', 'İplik ve Elyaf', 'iplik-elyaf'),
  ('iplik', 'en', 'Yarn and Fibre', 'yarn-fibre'),
  ('iplik', 'ru', 'Пряжа и волокно', 'pryazha-volokno'),
  ('orme-giyim', 'tr', 'Örme Giyim', 'orme-giyim'),
  ('orme-giyim', 'en', 'Knitwear', 'knitwear'),
  ('orme-giyim', 'ru', 'Трикотаж', 'trikotazh'),
  ('dokuma-giyim', 'tr', 'Dokuma Giyim', 'dokuma-giyim'),
  ('dokuma-giyim', 'en', 'Woven Apparel', 'woven-apparel'),
  ('dokuma-giyim', 'ru', 'Тканая одежда', 'tkanaya-odezhda'),
  ('is-elbisesi-uniforma', 'tr', 'İş Elbisesi ve Üniforma', 'is-elbisesi-uniforma'),
  ('is-elbisesi-uniforma', 'en', 'Workwear and Uniforms', 'workwear-uniforms'),
  ('is-elbisesi-uniforma', 'ru', 'Спецодежда и униформа', 'spetsodezhda-uniforma'),
  ('ev-tekstili', 'tr', 'Ev Tekstili', 'ev-tekstili'),
  ('ev-tekstili', 'en', 'Home Textiles', 'home-textiles'),
  ('ev-tekstili', 'ru', 'Домашний текстиль', 'domashniy-tekstil'),
  ('havlu-bornoz', 'tr', 'Havlu ve Bornoz', 'havlu-bornoz'),
  ('havlu-bornoz', 'en', 'Towels and Bathrobes', 'towels-bathrobes'),
  ('havlu-bornoz', 'ru', 'Полотенца и халаты', 'polotentsa-khalaty'),
  ('corap', 'tr', 'Çorap', 'corap'),
  ('corap', 'en', 'Socks and Hosiery', 'socks-hosiery'),
  ('corap', 'ru', 'Носки и чулки', 'noski-chulki'),
  ('deri-ayakkabi', 'tr', 'Deri ve Ayakkabı', 'deri-ayakkabi'),
  ('deri-ayakkabi', 'en', 'Leather and Footwear', 'leather-footwear'),
  ('deri-ayakkabi', 'ru', 'Кожа и обувь', 'kozha-obuv'),
  ('teknik-tekstil', 'tr', 'Teknik Tekstil', 'teknik-tekstil'),
  ('teknik-tekstil', 'en', 'Technical Textiles', 'technical-textiles'),
  ('teknik-tekstil', 'ru', 'Технический текстиль', 'tekhnicheskiy-tekstil'),
  ('aksesuar-tuhafiye', 'tr', 'Aksesuar ve Tuhafiye', 'aksesuar-tuhafiye'),
  ('aksesuar-tuhafiye', 'en', 'Trims and Accessories', 'trims-accessories'),
  ('aksesuar-tuhafiye', 'ru', 'Фурнитура и аксессуары', 'furnitura-aksessuary'),
  ('gida', 'tr', 'Gıda ve İçecek', 'gida-icecek'),
  ('gida', 'en', 'Food and Beverage', 'food-beverage'),
  ('gida', 'ru', 'Продукты и напитки', 'produkty-napitki'),
  ('kuru-gida', 'tr', 'Kuru Gıda ve Bakliyat', 'kuru-gida-bakliyat'),
  ('kuru-gida', 'en', 'Dry Goods and Pulses', 'dry-goods-pulses'),
  ('kuru-gida', 'ru', 'Крупы и бобовые', 'krupy-bobovye'),
  ('kuruyemis-kuru-meyve', 'tr', 'Kuruyemiş ve Kuru Meyve', 'kuruyemis-kuru-meyve'),
  ('kuruyemis-kuru-meyve', 'en', 'Nuts and Dried Fruit', 'nuts-dried-fruit'),
  ('kuruyemis-kuru-meyve', 'ru', 'Орехи и сухофрукты', 'orekhi-sukhofrukty'),
  ('un-unlu-mamul', 'tr', 'Un ve Unlu Mamul', 'un-unlu-mamul'),
  ('un-unlu-mamul', 'en', 'Flour and Bakery', 'flour-bakery'),
  ('un-unlu-mamul', 'ru', 'Мука и выпечка', 'muka-vypechka'),
  ('yag-zeytinyagi', 'tr', 'Yağ ve Zeytinyağı', 'yag-zeytinyagi'),
  ('yag-zeytinyagi', 'en', 'Oils and Olive Oil', 'oils-olive-oil'),
  ('yag-zeytinyagi', 'ru', 'Масла и оливковое масло', 'masla-olivkovoe'),
  ('sut-urunleri', 'tr', 'Süt ve Süt Ürünleri', 'sut-urunleri'),
  ('sut-urunleri', 'en', 'Dairy', 'dairy'),
  ('sut-urunleri', 'ru', 'Молочные продукты', 'molochnye-produkty'),
  ('et-urunleri', 'tr', 'Et ve Et Ürünleri', 'et-urunleri'),
  ('et-urunleri', 'en', 'Meat Products', 'meat-products'),
  ('et-urunleri', 'ru', 'Мясные продукты', 'myasnye-produkty'),
  ('su-urunleri', 'tr', 'Su Ürünleri', 'su-urunleri'),
  ('su-urunleri', 'en', 'Seafood', 'seafood'),
  ('su-urunleri', 'ru', 'Морепродукты', 'moreprodukty'),
  ('taze-meyve-sebze', 'tr', 'Taze Meyve Sebze', 'taze-meyve-sebze'),
  ('taze-meyve-sebze', 'en', 'Fresh Produce', 'fresh-produce'),
  ('taze-meyve-sebze', 'ru', 'Свежие фрукты и овощи', 'svezhie-frukty-ovoshchi'),
  ('dondurulmus-gida', 'tr', 'Dondurulmuş Gıda', 'dondurulmus-gida'),
  ('dondurulmus-gida', 'en', 'Frozen Food', 'frozen-food'),
  ('dondurulmus-gida', 'ru', 'Замороженные продукты', 'zamorozhennye-produkty'),
  ('sekerleme-cikolata', 'tr', 'Şekerleme ve Çikolata', 'sekerleme-cikolata'),
  ('sekerleme-cikolata', 'en', 'Confectionery', 'confectionery'),
  ('sekerleme-cikolata', 'ru', 'Кондитерские изделия', 'konditerskie-izdeliya'),
  ('icecek', 'tr', 'İçecek', 'icecek'),
  ('icecek', 'en', 'Beverages', 'beverages'),
  ('icecek', 'ru', 'Напитки', 'napitki'),
  ('baharat-cesni', 'tr', 'Baharat ve Çeşni', 'baharat-cesni'),
  ('baharat-cesni', 'en', 'Spices and Seasonings', 'spices-seasonings'),
  ('baharat-cesni', 'ru', 'Специи и приправы', 'spetsii-pripravy'),
  ('gida-katki', 'tr', 'Gıda Katkı Maddeleri', 'gida-katki'),
  ('gida-katki', 'en', 'Food Additives', 'food-additives'),
  ('gida-katki', 'ru', 'Пищевые добавки', 'pishchevye-dobavki'),
  ('yapi', 'tr', 'Yapı ve İnşaat', 'yapi-insaat'),
  ('yapi', 'en', 'Construction and Building', 'construction-building'),
  ('yapi', 'ru', 'Строительство', 'stroitelstvo'),
  ('cimento-beton', 'tr', 'Çimento ve Beton', 'cimento-beton'),
  ('cimento-beton', 'en', 'Cement and Concrete', 'cement-concrete'),
  ('cimento-beton', 'ru', 'Цемент и бетон', 'tsement-beton'),
  ('seramik-karo', 'tr', 'Seramik ve Karo', 'seramik-karo'),
  ('seramik-karo', 'en', 'Ceramics and Tiles', 'ceramics-tiles'),
  ('seramik-karo', 'ru', 'Керамика и плитка', 'keramika-plitka'),
  ('dogal-tas-mermer', 'tr', 'Doğal Taş ve Mermer', 'dogal-tas-mermer'),
  ('dogal-tas-mermer', 'en', 'Natural Stone and Marble', 'natural-stone-marble'),
  ('dogal-tas-mermer', 'ru', 'Природный камень', 'prirodnyy-kamen'),
  ('yalitim', 'tr', 'Yalıtım Malzemeleri', 'yalitim'),
  ('yalitim', 'en', 'Insulation', 'insulation'),
  ('yalitim', 'ru', 'Изоляция', 'izolyatsiya'),
  ('boya-vernik', 'tr', 'Boya ve Vernik', 'boya-vernik'),
  ('boya-vernik', 'en', 'Paint and Coatings', 'paint-coatings'),
  ('boya-vernik', 'ru', 'Краски и покрытия', 'kraski-pokrytiya'),
  ('kapi-pencere', 'tr', 'Kapı ve Pencere', 'kapi-pencere'),
  ('kapi-pencere', 'en', 'Doors and Windows', 'doors-windows'),
  ('kapi-pencere', 'ru', 'Двери и окна', 'dveri-okna'),
  ('tesisat-boru', 'tr', 'Tesisat ve Boru', 'tesisat-boru'),
  ('tesisat-boru', 'en', 'Plumbing and Pipes', 'plumbing-pipes'),
  ('tesisat-boru', 'ru', 'Сантехника и трубы', 'santekhnika-truby'),
  ('yapi-kimyasallari', 'tr', 'Yapı Kimyasalları', 'yapi-kimyasallari'),
  ('yapi-kimyasallari', 'en', 'Construction Chemicals', 'construction-chemicals'),
  ('yapi-kimyasallari', 'ru', 'Строительная химия', 'stroitelnaya-khimiya'),
  ('cati-cephe', 'tr', 'Çatı ve Cephe', 'cati-cephe'),
  ('cati-cephe', 'en', 'Roofing and Facade', 'roofing-facade'),
  ('cati-cephe', 'ru', 'Кровля и фасад', 'krovlya-fasad'),
  ('zemin-kaplama', 'tr', 'Zemin Kaplama', 'zemin-kaplama'),
  ('zemin-kaplama', 'en', 'Flooring', 'flooring'),
  ('zemin-kaplama', 'ru', 'Напольные покрытия', 'napolnye-pokrytiya'),
  ('prefabrik-konteyner', 'tr', 'Prefabrik ve Konteyner Yapı', 'prefabrik-konteyner'),
  ('prefabrik-konteyner', 'en', 'Prefab and Modular', 'prefab-modular'),
  ('prefabrik-konteyner', 'ru', 'Модульные здания', 'modulnye-zdaniya'),
  ('makine', 'tr', 'Makine ve Ekipman', 'makine-ekipman'),
  ('makine', 'en', 'Machinery and Equipment', 'machinery-equipment'),
  ('makine', 'ru', 'Машины и оборудование', 'mashiny-oborudovanie'),
  ('gida-isleme-makineleri', 'tr', 'Gıda İşleme Makineleri', 'gida-isleme-makineleri'),
  ('gida-isleme-makineleri', 'en', 'Food Processing Machinery', 'food-processing-machinery'),
  ('gida-isleme-makineleri', 'ru', 'Пищевое оборудование', 'pishchevoe-oborudovanie'),
  ('tekstil-makineleri', 'tr', 'Tekstil Makineleri', 'tekstil-makineleri'),
  ('tekstil-makineleri', 'en', 'Textile Machinery', 'textile-machinery'),
  ('tekstil-makineleri', 'ru', 'Текстильное оборудование', 'tekstilnoe-oborudovanie'),
  ('ambalaj-makineleri', 'tr', 'Ambalaj Makineleri', 'ambalaj-makineleri'),
  ('ambalaj-makineleri', 'en', 'Packaging Machinery', 'packaging-machinery'),
  ('ambalaj-makineleri', 'ru', 'Упаковочное оборудование', 'upakovochnoe-oborudovanie'),
  ('plastik-makineleri', 'tr', 'Plastik İşleme Makineleri', 'plastik-makineleri'),
  ('plastik-makineleri', 'en', 'Plastics Machinery', 'plastics-machinery'),
  ('plastik-makineleri', 'ru', 'Оборудование для пластмасс', 'oborudovanie-plastmassy'),
  ('cnc-tezgah', 'tr', 'Metal İşleme ve CNC', 'metal-isleme-cnc'),
  ('cnc-tezgah', 'en', 'Metalworking and CNC', 'metalworking-cnc'),
  ('cnc-tezgah', 'ru', 'Металлообработка и ЧПУ', 'metalloobrabotka-chpu'),
  ('tarim-makineleri', 'tr', 'Tarım Makineleri', 'tarim-makineleri'),
  ('tarim-makineleri', 'en', 'Agricultural Machinery', 'agricultural-machinery'),
  ('tarim-makineleri', 'ru', 'Сельхозтехника', 'selkhoztekhnika'),
  ('is-makineleri', 'tr', 'İş Makineleri', 'is-makineleri'),
  ('is-makineleri', 'en', 'Construction Machinery', 'construction-machinery'),
  ('is-makineleri', 'ru', 'Строительная техника', 'stroitelnaya-tekhnika'),
  ('kompresor-pompa', 'tr', 'Kompresör ve Pompa', 'kompresor-pompa'),
  ('kompresor-pompa', 'en', 'Compressors and Pumps', 'compressors-pumps'),
  ('kompresor-pompa', 'ru', 'Компрессоры и насосы', 'kompressory-nasosy'),
  ('jenerator-enerji', 'tr', 'Jeneratör ve Enerji', 'jenerator-enerji'),
  ('jenerator-enerji', 'en', 'Generators and Power', 'generators-power'),
  ('jenerator-enerji', 'ru', 'Генераторы и энергия', 'generatory-energiya'),
  ('yedek-parca-rulman', 'tr', 'Yedek Parça ve Rulman', 'yedek-parca-rulman'),
  ('yedek-parca-rulman', 'en', 'Spare Parts and Bearings', 'spare-parts-bearings'),
  ('yedek-parca-rulman', 'ru', 'Запчасти и подшипники', 'zapchasti-podshipniki'),
  ('kimya', 'tr', 'Kimya ve Petrokimya', 'kimya-petrokimya'),
  ('kimya', 'en', 'Chemicals and Petrochemicals', 'chemicals-petrochemicals'),
  ('kimya', 'ru', 'Химия и нефтехимия', 'khimiya-neftekhimiya'),
  ('endustriyel-kimyasallar', 'tr', 'Endüstriyel Kimyasallar', 'endustriyel-kimyasallar'),
  ('endustriyel-kimyasallar', 'en', 'Industrial Chemicals', 'industrial-chemicals'),
  ('endustriyel-kimyasallar', 'ru', 'Промышленная химия', 'promyshlennaya-khimiya'),
  ('polimer-recine', 'tr', 'Polimer ve Reçine', 'polimer-recine'),
  ('polimer-recine', 'en', 'Polymers and Resins', 'polymers-resins'),
  ('polimer-recine', 'ru', 'Полимеры и смолы', 'polimery-smoly'),
  ('pigment-boyarmadde', 'tr', 'Boya Hammaddesi ve Pigment', 'pigment-boyarmadde'),
  ('pigment-boyarmadde', 'en', 'Pigments and Dyes', 'pigments-dyes'),
  ('pigment-boyarmadde', 'ru', 'Пигменты и красители', 'pigmenty-krasiteli'),
  ('yapistirici', 'tr', 'Yapıştırıcı ve Kimyasal', 'yapistirici'),
  ('yapistirici', 'en', 'Adhesives', 'adhesives'),
  ('yapistirici', 'ru', 'Клеи', 'klei'),
  ('temizlik-kimyasallari', 'tr', 'Temizlik Kimyasalları', 'temizlik-kimyasallari'),
  ('temizlik-kimyasallari', 'en', 'Cleaning Chemicals', 'cleaning-chemicals'),
  ('temizlik-kimyasallari', 'ru', 'Моющая химия', 'moyushchaya-khimiya'),
  ('gubre-tarim-kimyasi', 'tr', 'Gübre ve Tarım Kimyası', 'gubre-tarim-kimyasi'),
  ('gubre-tarim-kimyasi', 'en', 'Fertilizers and Agrochemicals', 'fertilizers-agrochemicals'),
  ('gubre-tarim-kimyasi', 'ru', 'Удобрения и агрохимия', 'udobreniya-agrokhimiya'),
  ('laboratuvar-kimyasallari', 'tr', 'Laboratuvar Kimyasalları', 'laboratuvar-kimyasallari'),
  ('laboratuvar-kimyasallari', 'en', 'Laboratory Chemicals', 'laboratory-chemicals'),
  ('laboratuvar-kimyasallari', 'ru', 'Лабораторная химия', 'laboratornaya-khimiya'),
  ('madeni-yag', 'tr', 'Yağlar ve Madeni Yağ', 'madeni-yag'),
  ('madeni-yag', 'en', 'Lubricants', 'lubricants'),
  ('madeni-yag', 'ru', 'Смазочные материалы', 'smazochnye-materialy'),
  ('plastik', 'tr', 'Plastik ve Kauçuk', 'plastik-kaucuk'),
  ('plastik', 'en', 'Plastics and Rubber', 'plastics-rubber'),
  ('plastik', 'ru', 'Пластик и резина', 'plastik-rezina'),
  ('plastik-hammadde', 'tr', 'Plastik Hammadde', 'plastik-hammadde'),
  ('plastik-hammadde', 'en', 'Plastic Raw Material', 'plastic-raw-material'),
  ('plastik-hammadde', 'ru', 'Пластиковое сырьё', 'plastikovoe-syre'),
  ('enjeksiyon-urunleri', 'tr', 'Enjeksiyon Ürünleri', 'enjeksiyon-urunleri'),
  ('enjeksiyon-urunleri', 'en', 'Injection Moulded Parts', 'injection-moulded-parts'),
  ('enjeksiyon-urunleri', 'ru', 'Литьё под давлением', 'litye-pod-davleniem'),
  ('plastik-kasa-bidon', 'tr', 'Plastik Kasa ve Bidon', 'plastik-kasa-bidon'),
  ('plastik-kasa-bidon', 'en', 'Crates and Drums', 'crates-drums'),
  ('plastik-kasa-bidon', 'ru', 'Ящики и бочки', 'yashchiki-bochki'),
  ('plastik-boru-profil', 'tr', 'Boru ve Profil', 'plastik-boru-profil'),
  ('plastik-boru-profil', 'en', 'Pipes and Profiles', 'pipes-profiles'),
  ('plastik-boru-profil', 'ru', 'Трубы и профили', 'truby-profili'),
  ('kaucuk-conta', 'tr', 'Kauçuk ve Conta', 'kaucuk-conta'),
  ('kaucuk-conta', 'en', 'Rubber and Seals', 'rubber-seals'),
  ('kaucuk-conta', 'ru', 'Резина и уплотнители', 'rezina-uplotniteli'),
  ('levha-film', 'tr', 'Levha ve Film', 'levha-film'),
  ('levha-film', 'en', 'Sheets and Films', 'sheets-films'),
  ('levha-film', 'ru', 'Листы и плёнки', 'listy-plenki'),
  ('metal-madencilik', 'tr', 'Metal ve Madencilik', 'metal-madencilik'),
  ('metal-madencilik', 'en', 'Metals and Mining', 'metals-mining'),
  ('metal-madencilik', 'ru', 'Металлы и добыча', 'metally-dobycha'),
  ('demir-celik', 'tr', 'Demir ve Çelik', 'demir-celik'),
  ('demir-celik', 'en', 'Iron and Steel', 'iron-steel'),
  ('demir-celik', 'ru', 'Чёрные металлы', 'chernye-metally'),
  ('paslanmaz-celik', 'tr', 'Paslanmaz Çelik', 'paslanmaz-celik'),
  ('paslanmaz-celik', 'en', 'Stainless Steel', 'stainless-steel'),
  ('paslanmaz-celik', 'ru', 'Нержавеющая сталь', 'nerzhaveyushchaya-stal'),
  ('aluminyum', 'tr', 'Alüminyum', 'aluminyum'),
  ('aluminyum', 'en', 'Aluminium', 'aluminium'),
  ('aluminyum', 'ru', 'Алюминий', 'alyuminiy'),
  ('bakir-pirinc', 'tr', 'Bakır ve Pirinç', 'bakir-pirinc'),
  ('bakir-pirinc', 'en', 'Copper and Brass', 'copper-brass'),
  ('bakir-pirinc', 'ru', 'Медь и латунь', 'med-latun'),
  ('sac-profil', 'tr', 'Sac ve Profil', 'sac-profil'),
  ('sac-profil', 'en', 'Sheet and Profile', 'sheet-profile'),
  ('sac-profil', 'ru', 'Лист и профиль', 'list-profil'),
  ('dokum-talasli-imalat', 'tr', 'Döküm ve Talaşlı İmalat', 'dokum-talasli-imalat'),
  ('dokum-talasli-imalat', 'en', 'Casting and Machining', 'casting-machining'),
  ('dokum-talasli-imalat', 'ru', 'Литьё и обработка', 'litye-obrabotka'),
  ('maden-cevher', 'tr', 'Maden ve Cevher', 'maden-cevher'),
  ('maden-cevher', 'en', 'Minerals and Ores', 'minerals-ores'),
  ('maden-cevher', 'ru', 'Минералы и руды', 'mineraly-rudy'),
  ('hurda-geri-donusum', 'tr', 'Hurda ve Geri Dönüşüm', 'hurda-geri-donusum'),
  ('hurda-geri-donusum', 'en', 'Scrap and Recycling', 'scrap-recycling'),
  ('hurda-geri-donusum', 'ru', 'Лом и переработка', 'lom-pererabotka'),
  ('elektronik', 'tr', 'Elektrik ve Elektronik', 'elektrik-elektronik'),
  ('elektronik', 'en', 'Electrical and Electronics', 'electrical-electronics'),
  ('elektronik', 'ru', 'Электрика и электроника', 'elektrika-elektronika'),
  ('kablo-konnektor', 'tr', 'Kablo ve İletken', 'kablo-iletken'),
  ('kablo-konnektor', 'en', 'Cables and Wiring', 'cables-wiring'),
  ('kablo-konnektor', 'ru', 'Кабели и провода', 'kabeli-provoda'),
  ('aydinlatma', 'tr', 'Aydınlatma ve LED', 'aydinlatma-led'),
  ('aydinlatma', 'en', 'Lighting and LED', 'lighting-led'),
  ('aydinlatma', 'ru', 'Освещение и LED', 'osveshchenie-led'),
  ('pano-salt', 'tr', 'Elektrik Panosu ve Şalt', 'pano-salt'),
  ('pano-salt', 'en', 'Switchgear and Panels', 'switchgear-panels'),
  ('pano-salt', 'ru', 'Щиты и коммутация', 'shchity-kommutatsiya'),
  ('elektronik-modul', 'tr', 'Elektronik Bileşen', 'elektronik-bilesen'),
  ('elektronik-modul', 'en', 'Electronic Components', 'electronic-components'),
  ('elektronik-modul', 'ru', 'Электронные компоненты', 'elektronnye-komponenty'),
  ('gunes-enerjisi-panel', 'tr', 'Güneş Enerjisi ve Panel', 'gunes-enerjisi-panel'),
  ('gunes-enerjisi-panel', 'en', 'Solar and PV', 'solar-pv'),
  ('gunes-enerjisi-panel', 'ru', 'Солнечная энергетика', 'solnechnaya-energetika'),
  ('batarya-enerji-depolama', 'tr', 'Batarya ve Enerji Depolama', 'batarya-enerji-depolama'),
  ('batarya-enerji-depolama', 'en', 'Batteries and Storage', 'batteries-storage'),
  ('batarya-enerji-depolama', 'ru', 'Батареи и накопители', 'batarei-nakopiteli'),
  ('beyaz-esya-kucuk-ev', 'tr', 'Beyaz Eşya ve Küçük Ev Aleti', 'beyaz-esya-kucuk-ev'),
  ('beyaz-esya-kucuk-ev', 'en', 'Appliances', 'appliances'),
  ('beyaz-esya-kucuk-ev', 'ru', 'Бытовая техника', 'bytovaya-tekhnika'),
  ('bilisim-donanimi', 'tr', 'Bilişim Donanımı', 'bilisim-donanimi'),
  ('bilisim-donanimi', 'en', 'IT Hardware', 'it-hardware'),
  ('bilisim-donanimi', 'ru', 'ИТ-оборудование', 'it-oborudovanie'),
  ('otomotiv', 'tr', 'Otomotiv ve Yedek Parça', 'otomotiv-yedek-parca'),
  ('otomotiv', 'en', 'Automotive and Parts', 'automotive-parts'),
  ('otomotiv', 'ru', 'Автомобили и запчасти', 'avtomobili-zapchasti'),
  ('motor-sanziman', 'tr', 'Motor ve Şanzıman Parçaları', 'motor-sanziman'),
  ('motor-sanziman', 'en', 'Engine and Transmission', 'engine-transmission'),
  ('motor-sanziman', 'ru', 'Двигатель и трансмиссия', 'dvigatel-transmissiya'),
  ('fren-suspansiyon', 'tr', 'Fren ve Süspansiyon', 'fren-suspansiyon'),
  ('fren-suspansiyon', 'en', 'Brake and Suspension', 'brake-suspension'),
  ('fren-suspansiyon', 'ru', 'Тормоза и подвеска', 'tormoza-podveska'),
  ('kaporta-aksesuar', 'tr', 'Kaporta ve Aksesuar', 'kaporta-aksesuar'),
  ('kaporta-aksesuar', 'en', 'Body Parts and Accessories', 'body-parts-accessories'),
  ('kaporta-aksesuar', 'ru', 'Кузов и аксессуары', 'kuzov-aksessuary'),
  ('lastik', 'tr', 'Lastik ve Jant', 'lastik-jant'),
  ('lastik', 'en', 'Tyres and Wheels', 'tyres-wheels'),
  ('lastik', 'ru', 'Шины и диски', 'shiny-diski'),
  ('oto-elektrik', 'tr', 'Oto Elektrik', 'oto-elektrik'),
  ('oto-elektrik', 'en', 'Automotive Electrics', 'automotive-electrics'),
  ('oto-elektrik', 'ru', 'Автоэлектрика', 'avtoelektrika'),
  ('ticari-arac-romork', 'tr', 'Ticari Araç ve Römork', 'ticari-arac-romork'),
  ('ticari-arac-romork', 'en', 'Commercial Vehicles and Trailers', 'commercial-vehicles-trailers'),
  ('ticari-arac-romork', 'ru', 'Коммерческий транспорт', 'kommercheskiy-transport'),
  ('oto-kimyasallari', 'tr', 'Oto Kimyasalları', 'oto-kimyasallari'),
  ('oto-kimyasallari', 'en', 'Automotive Chemicals', 'automotive-chemicals'),
  ('oto-kimyasallari', 'ru', 'Автохимия', 'avtokhimiya'),
  ('mobilya-ev-yasam', 'tr', 'Mobilya ve Ev Yaşam', 'mobilya-ev-yasam'),
  ('mobilya-ev-yasam', 'en', 'Furniture and Home', 'furniture-home'),
  ('mobilya-ev-yasam', 'ru', 'Мебель и дом', 'mebel-dom'),
  ('ofis-mobilyasi', 'tr', 'Ofis Mobilyası', 'ofis-mobilyasi'),
  ('ofis-mobilyasi', 'en', 'Office Furniture', 'office-furniture'),
  ('ofis-mobilyasi', 'ru', 'Офисная мебель', 'ofisnaya-mebel'),
  ('ev-mobilyasi', 'tr', 'Ev Mobilyası', 'ev-mobilyasi'),
  ('ev-mobilyasi', 'en', 'Home Furniture', 'home-furniture'),
  ('ev-mobilyasi', 'ru', 'Домашняя мебель', 'domashnyaya-mebel'),
  ('otel-kontrat-mobilya', 'tr', 'Otel ve Kontrat Mobilya', 'otel-kontrat-mobilya'),
  ('otel-kontrat-mobilya', 'en', 'Hospitality and Contract', 'hospitality-contract'),
  ('otel-kontrat-mobilya', 'ru', 'Мебель для отелей', 'mebel-dlya-oteley'),
  ('mutfak-banyo', 'tr', 'Mutfak ve Banyo', 'mutfak-banyo'),
  ('mutfak-banyo', 'en', 'Kitchen and Bath', 'kitchen-bath'),
  ('mutfak-banyo', 'ru', 'Кухня и ванная', 'kukhnya-vannaya'),
  ('bahce-dis-mekan', 'tr', 'Bahçe ve Dış Mekân', 'bahce-dis-mekan'),
  ('bahce-dis-mekan', 'en', 'Garden and Outdoor', 'garden-outdoor'),
  ('bahce-dis-mekan', 'ru', 'Сад и улица', 'sad-ulitsa'),
  ('ev-dekorasyon', 'tr', 'Ev Dekorasyon', 'ev-dekorasyon'),
  ('ev-dekorasyon', 'en', 'Home Decor', 'home-decor'),
  ('ev-dekorasyon', 'ru', 'Декор для дома', 'dekor-dlya-doma'),
  ('mobilya-aksesuari', 'tr', 'Mobilya Aksesuarı', 'mobilya-aksesuari'),
  ('mobilya-aksesuari', 'en', 'Furniture Hardware', 'furniture-hardware'),
  ('mobilya-aksesuari', 'ru', 'Мебельная фурнитура', 'mebelnaya-furnitura'),
  ('kozmetik', 'tr', 'Kozmetik ve Kişisel Bakım', 'kozmetik-kisisel-bakim'),
  ('kozmetik', 'en', 'Cosmetics and Personal Care', 'cosmetics-personal-care'),
  ('kozmetik', 'ru', 'Косметика и уход', 'kosmetika-ukhod'),
  ('cilt-bakimi', 'tr', 'Cilt Bakımı', 'cilt-bakimi'),
  ('cilt-bakimi', 'en', 'Skin Care', 'skin-care'),
  ('cilt-bakimi', 'ru', 'Уход за кожей', 'ukhod-za-kozhey'),
  ('sac-bakimi', 'tr', 'Saç Bakımı', 'sac-bakimi'),
  ('sac-bakimi', 'en', 'Hair Care', 'hair-care'),
  ('sac-bakimi', 'ru', 'Уход за волосами', 'ukhod-za-volosami'),
  ('makyaj', 'tr', 'Makyaj', 'makyaj'),
  ('makyaj', 'en', 'Make-up', 'make-up'),
  ('makyaj', 'ru', 'Макияж', 'makiyazh'),
  ('parfum-deodorant', 'tr', 'Parfüm ve Deodorant', 'parfum-deodorant'),
  ('parfum-deodorant', 'en', 'Fragrance and Deodorant', 'fragrance-deodorant'),
  ('parfum-deodorant', 'ru', 'Парфюмерия и дезодоранты', 'parfyumeriya-dezodoranty'),
  ('sabun-dus', 'tr', 'Sabun ve Duş Ürünleri', 'sabun-dus'),
  ('sabun-dus', 'en', 'Soap and Bath', 'soap-bath'),
  ('sabun-dus', 'ru', 'Мыло и гели для душа', 'mylo-geli'),
  ('bebek-bakim', 'tr', 'Bebek Bakım', 'bebek-bakim'),
  ('bebek-bakim', 'en', 'Baby Care', 'baby-care'),
  ('bebek-bakim', 'ru', 'Детский уход', 'detskiy-ukhod'),
  ('ozel-uretim-private-label', 'tr', 'Özel Üretim (Private Label)', 'ozel-uretim-private-label'),
  ('ozel-uretim-private-label', 'en', 'Private Label', 'private-label'),
  ('ozel-uretim-private-label', 'ru', 'Private label', 'private-label'),
  ('temizlik-hijyen', 'tr', 'Temizlik ve Hijyen', 'temizlik-hijyen'),
  ('temizlik-hijyen', 'en', 'Cleaning and Hygiene', 'cleaning-hygiene'),
  ('temizlik-hijyen', 'ru', 'Уборка и гигиена', 'uborka-gigiena'),
  ('endustriyel-temizlik', 'tr', 'Endüstriyel Temizlik', 'endustriyel-temizlik'),
  ('endustriyel-temizlik', 'en', 'Industrial Cleaning', 'industrial-cleaning'),
  ('endustriyel-temizlik', 'ru', 'Промышленная уборка', 'promyshlennaya-uborka'),
  ('kagit-urunleri', 'tr', 'Kâğıt Ürünleri', 'kagit-urunleri'),
  ('kagit-urunleri', 'en', 'Paper Hygiene', 'paper-hygiene'),
  ('kagit-urunleri', 'ru', 'Бумажная гигиена', 'bumazhnaya-gigiena'),
  ('camasir-bulasik', 'tr', 'Çamaşır ve Bulaşık', 'camasir-bulasik'),
  ('camasir-bulasik', 'en', 'Laundry and Dishwash', 'laundry-dishwash'),
  ('camasir-bulasik', 'ru', 'Стирка и мытьё посуды', 'stirka-mytye-posudy'),
  ('dezenfektan', 'tr', 'Dezenfektan', 'dezenfektan'),
  ('dezenfektan', 'en', 'Disinfectants', 'disinfectants'),
  ('dezenfektan', 'ru', 'Дезинфекция', 'dezinfektsiya'),
  ('temizlik-ekipmani', 'tr', 'Temizlik Ekipmanı', 'temizlik-ekipmani'),
  ('temizlik-ekipmani', 'en', 'Cleaning Equipment', 'cleaning-equipment'),
  ('temizlik-ekipmani', 'ru', 'Уборочный инвентарь', 'uborochnyy-inventar'),
  ('medikal-saglik', 'tr', 'Medikal ve Sağlık', 'medikal-saglik'),
  ('medikal-saglik', 'en', 'Medical and Healthcare', 'medical-healthcare'),
  ('medikal-saglik', 'ru', 'Медицина и здоровье', 'meditsina-zdorove'),
  ('tibbi-sarf', 'tr', 'Tıbbi Sarf Malzeme', 'tibbi-sarf'),
  ('tibbi-sarf', 'en', 'Medical Consumables', 'medical-consumables'),
  ('tibbi-sarf', 'ru', 'Медицинские расходники', 'meditsinskie-raskhodniki'),
  ('tibbi-cihaz', 'tr', 'Tıbbi Cihaz', 'tibbi-cihaz'),
  ('tibbi-cihaz', 'en', 'Medical Devices', 'medical-devices'),
  ('tibbi-cihaz', 'ru', 'Медицинское оборудование', 'meditsinskoe-oborudovanie'),
  ('kisisel-koruyucu-donanim', 'tr', 'Kişisel Koruyucu Donanım', 'kisisel-koruyucu-donanim'),
  ('kisisel-koruyucu-donanim', 'en', 'PPE', 'ppe'),
  ('kisisel-koruyucu-donanim', 'ru', 'СИЗ', 'siz'),
  ('laboratuvar-ekipmani', 'tr', 'Laboratuvar Ekipmanı', 'laboratuvar-ekipmani'),
  ('laboratuvar-ekipmani', 'en', 'Laboratory Equipment', 'laboratory-equipment'),
  ('laboratuvar-ekipmani', 'ru', 'Лабораторное оборудование', 'laboratornoe-oborudovanie'),
  ('ilac-takviye', 'tr', 'İlaç ve Takviye', 'ilac-takviye'),
  ('ilac-takviye', 'en', 'Pharma and Supplements', 'pharma-supplements'),
  ('ilac-takviye', 'ru', 'Фармацевтика и добавки', 'farmatsevtika-dobavki'),
  ('ortopedi-rehabilitasyon', 'tr', 'Ortopedi ve Rehabilitasyon', 'ortopedi-rehabilitasyon'),
  ('ortopedi-rehabilitasyon', 'en', 'Orthopaedics', 'orthopaedics'),
  ('ortopedi-rehabilitasyon', 'ru', 'Ортопедия', 'ortopediya'),
  ('tarim-hayvancilik', 'tr', 'Tarım ve Hayvancılık', 'tarim-hayvancilik'),
  ('tarim-hayvancilik', 'en', 'Agriculture and Livestock', 'agriculture-livestock'),
  ('tarim-hayvancilik', 'ru', 'Сельское хозяйство', 'selskoe-khozyaystvo'),
  ('tohum-fide', 'tr', 'Tohum ve Fide', 'tohum-fide'),
  ('tohum-fide', 'en', 'Seeds and Seedlings', 'seeds-seedlings'),
  ('tohum-fide', 'ru', 'Семена и рассада', 'semena-rassada'),
  ('sera-ekipman', 'tr', 'Sera ve Ekipman', 'sera-ekipman'),
  ('sera-ekipman', 'en', 'Greenhouse Equipment', 'greenhouse-equipment'),
  ('sera-ekipman', 'ru', 'Тепличное оборудование', 'teplichnoe-oborudovanie'),
  ('sulama-sistemleri', 'tr', 'Sulama Sistemleri', 'sulama-sistemleri'),
  ('sulama-sistemleri', 'en', 'Irrigation', 'irrigation'),
  ('sulama-sistemleri', 'ru', 'Орошение', 'orosheniye'),
  ('yem-hayvan-besleme', 'tr', 'Yem ve Hayvan Besleme', 'yem-hayvan-besleme'),
  ('yem-hayvan-besleme', 'en', 'Feed and Nutrition', 'feed-nutrition'),
  ('yem-hayvan-besleme', 'ru', 'Корма', 'korma'),
  ('hayvancilik-ekipmani', 'tr', 'Hayvancılık Ekipmanı', 'hayvancilik-ekipmani'),
  ('hayvancilik-ekipmani', 'en', 'Livestock Equipment', 'livestock-equipment'),
  ('hayvancilik-ekipmani', 'ru', 'Животноводческое оборудование', 'zhivotnovodcheskoe-oborudovanie'),
  ('su-urunleri-yetistiriciligi', 'tr', 'Su Ürünleri Yetiştiriciliği', 'su-urunleri-yetistiriciligi'),
  ('su-urunleri-yetistiriciligi', 'en', 'Aquaculture', 'aquaculture'),
  ('su-urunleri-yetistiriciligi', 'ru', 'Аквакультура', 'akvakultura'),
  ('hirdavat', 'tr', 'Hırdavat ve El Aletleri', 'hirdavat-el-aletleri'),
  ('hirdavat', 'en', 'Hardware and Tools', 'hardware-tools'),
  ('hirdavat', 'ru', 'Скобяные изделия и инструмент', 'skobyanye-instrument'),
  ('el-aletleri', 'tr', 'El Aletleri', 'el-aletleri'),
  ('el-aletleri', 'en', 'Hand Tools', 'hand-tools'),
  ('el-aletleri', 'ru', 'Ручной инструмент', 'ruchnoy-instrument'),
  ('elektrikli-el-aleti', 'tr', 'Elektrikli El Aleti', 'elektrikli-el-aleti'),
  ('elektrikli-el-aleti', 'en', 'Power Tools', 'power-tools'),
  ('elektrikli-el-aleti', 'ru', 'Электроинструмент', 'elektroinstrument'),
  ('baglanti-elemanlari', 'tr', 'Bağlantı Elemanları', 'baglanti-elemanlari'),
  ('baglanti-elemanlari', 'en', 'Fasteners', 'fasteners'),
  ('baglanti-elemanlari', 'ru', 'Крепёж', 'krepezh'),
  ('kesici-takim', 'tr', 'Kesici Takım', 'kesici-takim'),
  ('kesici-takim', 'en', 'Cutting Tools', 'cutting-tools'),
  ('kesici-takim', 'ru', 'Режущий инструмент', 'rezhushchiy-instrument'),
  ('kilit-mentese', 'tr', 'Kilit ve Menteşe', 'kilit-mentese'),
  ('kilit-mentese', 'en', 'Locks and Hinges', 'locks-hinges'),
  ('kilit-mentese', 'ru', 'Замки и петли', 'zamki-petli'),
  ('is-guvenligi-ekipmani', 'tr', 'İş Güvenliği Ekipmanı', 'is-guvenligi-ekipmani'),
  ('is-guvenligi-ekipmani', 'en', 'Safety Equipment', 'safety-equipment'),
  ('is-guvenligi-ekipmani', 'ru', 'Средства безопасности', 'sredstva-bezopasnosti'),
  ('kirtasiye', 'tr', 'Kırtasiye ve Ofis', 'kirtasiye-ofis'),
  ('kirtasiye', 'en', 'Stationery and Office', 'stationery-office'),
  ('kirtasiye', 'ru', 'Канцтовары и офис', 'kanctovary-ofis'),
  ('kagit-defter', 'tr', 'Kâğıt ve Defter', 'kagit-defter'),
  ('kagit-defter', 'en', 'Paper and Notebooks', 'paper-notebooks'),
  ('kagit-defter', 'ru', 'Бумага и тетради', 'bumaga-tetradi'),
  ('yazi-gerecleri', 'tr', 'Yazı Gereçleri', 'yazi-gerecleri'),
  ('yazi-gerecleri', 'en', 'Writing Instruments', 'writing-instruments'),
  ('yazi-gerecleri', 'ru', 'Письменные принадлежности', 'pismennye-prinadlezhnosti'),
  ('ofis-sarf', 'tr', 'Ofis Sarf Malzemesi', 'ofis-sarf'),
  ('ofis-sarf', 'en', 'Office Supplies', 'office-supplies'),
  ('ofis-sarf', 'ru', 'Офисные расходники', 'ofisnye-raskhodniki'),
  ('baski-toner', 'tr', 'Baskı ve Toner', 'baski-toner'),
  ('baski-toner', 'en', 'Printing and Toner', 'printing-toner'),
  ('baski-toner', 'ru', 'Печать и тонеры', 'pechat-tonery'),
  ('promosyon-urunleri', 'tr', 'Promosyon Ürünleri', 'promosyon-urunleri'),
  ('promosyon-urunleri', 'en', 'Promotional Products', 'promotional-products'),
  ('promosyon-urunleri', 'ru', 'Промо-продукция', 'promo-produktsiya'),
  ('oyuncak-hobi-spor', 'tr', 'Oyuncak, Hobi ve Spor', 'oyuncak-hobi-spor'),
  ('oyuncak-hobi-spor', 'en', 'Toys, Hobby and Sports', 'toys-hobby-sports'),
  ('oyuncak-hobi-spor', 'ru', 'Игрушки, хобби и спорт', 'igrushki-khobbi-sport'),
  ('oyuncak', 'tr', 'Oyuncak', 'oyuncak'),
  ('oyuncak', 'en', 'Toys', 'toys'),
  ('oyuncak', 'ru', 'Игрушки', 'igrushki'),
  ('spor-malzemesi', 'tr', 'Spor Malzemesi', 'spor-malzemesi'),
  ('spor-malzemesi', 'en', 'Sporting Goods', 'sporting-goods'),
  ('spor-malzemesi', 'ru', 'Спорттовары', 'sporttovary'),
  ('kamp-outdoor', 'tr', 'Kamp ve Outdoor', 'kamp-outdoor'),
  ('kamp-outdoor', 'en', 'Camping and Outdoor', 'camping-outdoor'),
  ('kamp-outdoor', 'ru', 'Кемпинг и туризм', 'kemping-turizm'),
  ('hobi-el-sanatlari', 'tr', 'Hobi ve El Sanatları', 'hobi-el-sanatlari'),
  ('hobi-el-sanatlari', 'en', 'Hobby and Crafts', 'hobby-crafts'),
  ('hobi-el-sanatlari', 'ru', 'Хобби и рукоделие', 'khobbi-rukodelie'),
  ('parti-hediyelik', 'tr', 'Parti ve Hediyelik', 'parti-hediyelik'),
  ('parti-hediyelik', 'en', 'Party and Gifts', 'party-gifts'),
  ('parti-hediyelik', 'ru', 'Праздник и подарки', 'prazdnik-podarki'),
  ('lojistik-depolama', 'tr', 'Lojistik ve Depolama', 'lojistik-depolama'),
  ('lojistik-depolama', 'en', 'Logistics and Storage', 'logistics-storage'),
  ('lojistik-depolama', 'ru', 'Логистика и склад', 'logistika-sklad'),
  ('raf-depo-sistemleri', 'tr', 'Raf ve Depo Sistemleri', 'raf-depo-sistemleri'),
  ('raf-depo-sistemleri', 'en', 'Racking and Shelving', 'racking-shelving'),
  ('raf-depo-sistemleri', 'ru', 'Стеллажи', 'stellazhi'),
  ('istif-tasima-ekipmani', 'tr', 'İstif ve Taşıma Ekipmanı', 'istif-tasima-ekipmani'),
  ('istif-tasima-ekipmani', 'en', 'Material Handling', 'material-handling'),
  ('istif-tasima-ekipmani', 'ru', 'Погрузочная техника', 'pogruzochnaya-tekhnika'),
  ('soguk-zincir-ekipmani', 'tr', 'Soğuk Zincir Ekipmanı', 'soguk-zincir-ekipmani'),
  ('soguk-zincir-ekipmani', 'en', 'Cold Chain Equipment', 'cold-chain-equipment'),
  ('soguk-zincir-ekipmani', 'ru', 'Холодильное оборудование', 'kholodilnoe-oborudovanie'),
  ('konteyner-tasima-kabi', 'tr', 'Konteyner ve Taşıma Kabı', 'konteyner-tasima-kabi'),
  ('konteyner-tasima-kabi', 'en', 'Containers and Bins', 'containers-bins'),
  ('konteyner-tasima-kabi', 'ru', 'Контейнеры', 'konteynery')
) as v(base_slug, locale, name, slug)
join categories c on c.slug = v.base_slug
on conflict (category_id, locale) do update set
  name = excluded.name,
  slug = excluded.slug;
