-- ============================================================
-- Coğrafi referans: ülkeler, iller, ilçeler
--
-- Adres alanları serbest metindi: "İstanbul", "istanbul", "Istanbul" ve
-- "İSTANBUL" ayrı şehirler sayılıyordu. Şehir filtresi bu yüzden hem
-- eksik hem gürültülü sonuç veriyordu.
--
-- Kaynaklar (bir kez çekilip buraya gömüldü; çalışma zamanında ağ
-- bağımlılığı YOK):
--   iller/ilçeler : https://turkiyeapi.dev/api/v1/provinces  (81 il, 973 ilçe)
--   ülke adları   : github.com/umpirsky/country-list (en, tr, ru)
--
-- regions tablosu tek düzey ağaçtır (il → ilçe) ve country_code ile
-- başka ülkelere genişleyebilir; ihracat pazarları eklenecekse şema
-- değişikliği gerekmez.
-- ============================================================

create table if not exists countries (
  code        char(2) primary key,
  name_tr     text not null,
  name_en     text not null,
  name_ru     text not null,
  -- Türkiye listenin başında dursun; gerisi ada göre sıralanır.
  sort_order  smallint not null default 100
);

create table if not exists regions (
  id           uuid primary key default gen_random_uuid(),
  country_code char(2) not null references countries(code) on delete cascade,
  parent_id    uuid references regions(id) on delete cascade,
  level        smallint not null check (level in (1, 2)),
  -- İl için plaka kodu; ilçede boş.
  code         text,
  name         text not null,
  unique (country_code, level, parent_id, name)
);

comment on column regions.level is '1 = il / eyalet, 2 = ilçe';

create index if not exists regions_lookup_idx
  on regions (country_code, level, parent_id);

/*
  Kök bölgeler (iller) için AYRI tekillik kuralı gerekiyor.

  Tablodaki `unique (country_code, level, parent_id, name)` kısıtı iller
  için işlemiyor: parent_id NULL ve Postgres UNIQUE kısıtında NULL'ları
  birbirinden farklı sayar. Yani "TR/1/NULL/Adana" kendisiyle çakışmaz
  ve dosya ikinci kez çalıştırıldığında 81 il 162'ye çıkar.

  Kısmi indeks bunu kesin olarak engeller.
*/
create unique index if not exists regions_root_unique
  on regions (country_code, level, name) where parent_id is null;
create index if not exists regions_parent_idx on regions (parent_id);

-- Referans veridir: herkes okur, yalnızca yönetici yazar.
alter table countries enable row level security;
alter table regions enable row level security;

drop policy if exists "countries_read_all" on countries;
create policy "countries_read_all" on countries for select using (true);
drop policy if exists "countries_admin_write" on countries;
create policy "countries_admin_write" on countries for all
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "regions_read_all" on regions;
create policy "regions_read_all" on regions for select using (true);
drop policy if exists "regions_admin_write" on regions;
create policy "regions_admin_write" on regions for all
  using (public.is_admin()) with check (public.is_admin());

-- ---------- Ülkeler ----------
insert into countries (code, name_tr, name_en, name_ru, sort_order) values
  ('AD', 'Andorra', 'Andorra', 'Андорра', 100),
  ('AE', 'Birleşik Arap Emirlikleri', 'United Arab Emirates', 'ОАЭ', 100),
  ('AF', 'Afganistan', 'Afghanistan', 'Афганистан', 100),
  ('AG', 'Antigua ve Barbuda', 'Antigua & Barbuda', 'Антигуа и Барбуда', 100),
  ('AI', 'Anguilla', 'Anguilla', 'Ангилья', 100),
  ('AL', 'Arnavutluk', 'Albania', 'Албания', 100),
  ('AM', 'Ermenistan', 'Armenia', 'Армения', 100),
  ('AO', 'Angola', 'Angola', 'Ангола', 100),
  ('AQ', 'Antarktika', 'Antarctica', 'Антарктида', 100),
  ('AR', 'Arjantin', 'Argentina', 'Аргентина', 100),
  ('AS', 'Amerikan Samoası', 'American Samoa', 'Американское Самоа', 100),
  ('AT', 'Avusturya', 'Austria', 'Австрия', 100),
  ('AU', 'Avustralya', 'Australia', 'Австралия', 100),
  ('AW', 'Aruba', 'Aruba', 'Аруба', 100),
  ('AX', 'Åland Adaları', 'Åland Islands', 'Аландские о-ва', 100),
  ('AZ', 'Azerbaycan', 'Azerbaijan', 'Азербайджан', 100),
  ('BA', 'Bosna-Hersek', 'Bosnia & Herzegovina', 'Босния и Герцеговина', 100),
  ('BB', 'Barbados', 'Barbados', 'Барбадос', 100),
  ('BD', 'Bangladeş', 'Bangladesh', 'Бангладеш', 100),
  ('BE', 'Belçika', 'Belgium', 'Бельгия', 100),
  ('BF', 'Burkina Faso', 'Burkina Faso', 'Буркина-Фасо', 100),
  ('BG', 'Bulgaristan', 'Bulgaria', 'Болгария', 100),
  ('BH', 'Bahreyn', 'Bahrain', 'Бахрейн', 100),
  ('BI', 'Burundi', 'Burundi', 'Бурунди', 100),
  ('BJ', 'Benin', 'Benin', 'Бенин', 100),
  ('BL', 'Saint Barthelemy', 'St. Barthélemy', 'Сен-Бартелеми', 100),
  ('BM', 'Bermuda', 'Bermuda', 'Бермудские о-ва', 100),
  ('BN', 'Brunei', 'Brunei', 'Бруней-Даруссалам', 100),
  ('BO', 'Bolivya', 'Bolivia', 'Боливия', 100),
  ('BQ', 'Karayip Hollandası', 'Caribbean Netherlands', 'Бонэйр, Синт-Эстатиус и Саба', 100),
  ('BR', 'Brezilya', 'Brazil', 'Бразилия', 100),
  ('BS', 'Bahamalar', 'Bahamas', 'Багамы', 100),
  ('BT', 'Butan', 'Bhutan', 'Бутан', 100),
  ('BV', 'Bouvet Adası', 'Bouvet Island', 'о-в Буве', 100),
  ('BW', 'Botsvana', 'Botswana', 'Ботсвана', 100),
  ('BY', 'Belarus', 'Belarus', 'Беларусь', 100),
  ('BZ', 'Belize', 'Belize', 'Белиз', 100),
  ('CA', 'Kanada', 'Canada', 'Канада', 100),
  ('CC', 'Cocos (Keeling) Adaları', 'Cocos (Keeling) Islands', 'Кокосовые о-ва', 100),
  ('CD', 'Kongo - Kinşasa', 'Congo - Kinshasa', 'Конго - Киншаса', 100),
  ('CF', 'Orta Afrika Cumhuriyeti', 'Central African Republic', 'Центрально-Африканская Республика', 100),
  ('CG', 'Kongo - Brazavil', 'Congo - Brazzaville', 'Конго - Браззавиль', 100),
  ('CH', 'İsviçre', 'Switzerland', 'Швейцария', 100),
  ('CI', 'Côte d’Ivoire', 'Côte d’Ivoire', 'Кот-д’Ивуар', 100),
  ('CK', 'Cook Adaları', 'Cook Islands', 'Острова Кука', 100),
  ('CL', 'Şili', 'Chile', 'Чили', 100),
  ('CM', 'Kamerun', 'Cameroon', 'Камерун', 100),
  ('CN', 'Çin', 'China', 'Китай', 100),
  ('CO', 'Kolombiya', 'Colombia', 'Колумбия', 100),
  ('CR', 'Kosta Rika', 'Costa Rica', 'Коста-Рика', 100),
  ('CU', 'Küba', 'Cuba', 'Куба', 100),
  ('CV', 'Cape Verde', 'Cape Verde', 'Кабо-Верде', 100),
  ('CW', 'Curaçao', 'Curaçao', 'Кюрасао', 100),
  ('CX', 'Christmas Adası', 'Christmas Island', 'о-в Рождества', 100),
  ('CY', 'Kıbrıs', 'Cyprus', 'Кипр', 100),
  ('CZ', 'Çekya', 'Czechia', 'Чехия', 100),
  ('DE', 'Almanya', 'Germany', 'Германия', 100),
  ('DJ', 'Cibuti', 'Djibouti', 'Джибути', 100),
  ('DK', 'Danimarka', 'Denmark', 'Дания', 100),
  ('DM', 'Dominika', 'Dominica', 'Доминика', 100),
  ('DO', 'Dominik Cumhuriyeti', 'Dominican Republic', 'Доминиканская Республика', 100),
  ('DZ', 'Cezayir', 'Algeria', 'Алжир', 100),
  ('EC', 'Ekvador', 'Ecuador', 'Эквадор', 100),
  ('EE', 'Estonya', 'Estonia', 'Эстония', 100),
  ('EG', 'Mısır', 'Egypt', 'Египет', 100),
  ('EH', 'Batı Sahra', 'Western Sahara', 'Западная Сахара', 100),
  ('ER', 'Eritre', 'Eritrea', 'Эритрея', 100),
  ('ES', 'İspanya', 'Spain', 'Испания', 100),
  ('ET', 'Etiyopya', 'Ethiopia', 'Эфиопия', 100),
  ('FI', 'Finlandiya', 'Finland', 'Финляндия', 100),
  ('FJ', 'Fiji', 'Fiji', 'Фиджи', 100),
  ('FK', 'Falkland Adaları', 'Falkland Islands', 'Фолклендские о-ва', 100),
  ('FM', 'Mikronezya', 'Micronesia', 'Федеративные Штаты Микронезии', 100),
  ('FO', 'Faroe Adaları', 'Faroe Islands', 'Фарерские о-ва', 100),
  ('FR', 'Fransa', 'France', 'Франция', 100),
  ('GA', 'Gabon', 'Gabon', 'Габон', 100),
  ('GB', 'Birleşik Krallık', 'United Kingdom', 'Великобритания', 100),
  ('GD', 'Grenada', 'Grenada', 'Гренада', 100),
  ('GE', 'Gürcistan', 'Georgia', 'Грузия', 100),
  ('GF', 'Fransız Guyanası', 'French Guiana', 'Французская Гвиана', 100),
  ('GG', 'Guernsey', 'Guernsey', 'Гернси', 100),
  ('GH', 'Gana', 'Ghana', 'Гана', 100),
  ('GI', 'Cebelitarık', 'Gibraltar', 'Гибралтар', 100),
  ('GL', 'Grönland', 'Greenland', 'Гренландия', 100),
  ('GM', 'Gambiya', 'Gambia', 'Гамбия', 100),
  ('GN', 'Gine', 'Guinea', 'Гвинея', 100),
  ('GP', 'Guadeloupe', 'Guadeloupe', 'Гваделупа', 100),
  ('GQ', 'Ekvator Ginesi', 'Equatorial Guinea', 'Экваториальная Гвинея', 100),
  ('GR', 'Yunanistan', 'Greece', 'Греция', 100),
  ('GS', 'Güney Georgia ve Güney Sandwich Adaları', 'South Georgia & South Sandwich Islands', 'Южная Георгия и Южные Сандвичевы о-ва', 100),
  ('GT', 'Guatemala', 'Guatemala', 'Гватемала', 100),
  ('GU', 'Guam', 'Guam', 'Гуам', 100),
  ('GW', 'Gine-Bissau', 'Guinea-Bissau', 'Гвинея-Бисау', 100),
  ('GY', 'Guyana', 'Guyana', 'Гайана', 100),
  ('HK', 'Çin Hong Kong ÖİB', 'Hong Kong SAR China', 'Гонконг (САР)', 100),
  ('HM', 'Heard Adası ve McDonald Adaları', 'Heard & McDonald Islands', 'о-ва Херд и Макдональд', 100),
  ('HN', 'Honduras', 'Honduras', 'Гондурас', 100),
  ('HR', 'Hırvatistan', 'Croatia', 'Хорватия', 100),
  ('HT', 'Haiti', 'Haiti', 'Гаити', 100),
  ('HU', 'Macaristan', 'Hungary', 'Венгрия', 100),
  ('ID', 'Endonezya', 'Indonesia', 'Индонезия', 100),
  ('IE', 'İrlanda', 'Ireland', 'Ирландия', 100),
  ('IL', 'İsrail', 'Israel', 'Израиль', 100),
  ('IM', 'Man Adası', 'Isle of Man', 'о-в Мэн', 100),
  ('IN', 'Hindistan', 'India', 'Индия', 100),
  ('IO', 'Britanya Hint Okyanusu Toprakları', 'British Indian Ocean Territory', 'Британская территория в Индийском океане', 100),
  ('IQ', 'Irak', 'Iraq', 'Ирак', 100),
  ('IR', 'İran', 'Iran', 'Иран', 100),
  ('IS', 'İzlanda', 'Iceland', 'Исландия', 100),
  ('IT', 'İtalya', 'Italy', 'Италия', 100),
  ('JE', 'Jersey', 'Jersey', 'Джерси', 100),
  ('JM', 'Jamaika', 'Jamaica', 'Ямайка', 100),
  ('JO', 'Ürdün', 'Jordan', 'Иордания', 100),
  ('JP', 'Japonya', 'Japan', 'Япония', 100),
  ('KE', 'Kenya', 'Kenya', 'Кения', 100),
  ('KG', 'Kırgızistan', 'Kyrgyzstan', 'Киргизия', 100),
  ('KH', 'Kamboçya', 'Cambodia', 'Камбоджа', 100),
  ('KI', 'Kiribati', 'Kiribati', 'Кирибати', 100),
  ('KM', 'Komorlar', 'Comoros', 'Коморы', 100),
  ('KN', 'Saint Kitts ve Nevis', 'St. Kitts & Nevis', 'Сент-Китс и Невис', 100),
  ('KP', 'Kuzey Kore', 'North Korea', 'КНДР', 100),
  ('KR', 'Güney Kore', 'South Korea', 'Республика Корея', 100),
  ('KW', 'Kuveyt', 'Kuwait', 'Кувейт', 100),
  ('KY', 'Cayman Adaları', 'Cayman Islands', 'Острова Кайман', 100),
  ('KZ', 'Kazakistan', 'Kazakhstan', 'Казахстан', 100),
  ('LA', 'Laos', 'Laos', 'Лаос', 100),
  ('LB', 'Lübnan', 'Lebanon', 'Ливан', 100),
  ('LC', 'Saint Lucia', 'St. Lucia', 'Сент-Люсия', 100),
  ('LI', 'Liechtenstein', 'Liechtenstein', 'Лихтенштейн', 100),
  ('LK', 'Sri Lanka', 'Sri Lanka', 'Шри-Ланка', 100),
  ('LR', 'Liberya', 'Liberia', 'Либерия', 100),
  ('LS', 'Lesotho', 'Lesotho', 'Лесото', 100),
  ('LT', 'Litvanya', 'Lithuania', 'Литва', 100),
  ('LU', 'Lüksemburg', 'Luxembourg', 'Люксембург', 100),
  ('LV', 'Letonya', 'Latvia', 'Латвия', 100),
  ('LY', 'Libya', 'Libya', 'Ливия', 100),
  ('MA', 'Fas', 'Morocco', 'Марокко', 100),
  ('MC', 'Monako', 'Monaco', 'Монако', 100),
  ('MD', 'Moldova', 'Moldova', 'Молдова', 100),
  ('ME', 'Karadağ', 'Montenegro', 'Черногория', 100),
  ('MF', 'Saint Martin', 'St. Martin', 'Сен-Мартен', 100),
  ('MG', 'Madagaskar', 'Madagascar', 'Мадагаскар', 100),
  ('MH', 'Marshall Adaları', 'Marshall Islands', 'Маршалловы Острова', 100),
  ('MK', 'Kuzey Makedonya', 'North Macedonia', 'Северная Македония', 100),
  ('ML', 'Mali', 'Mali', 'Мали', 100),
  ('MM', 'Myanmar (Burma)', 'Myanmar (Burma)', 'Мьянма (Бирма)', 100),
  ('MN', 'Moğolistan', 'Mongolia', 'Монголия', 100),
  ('MO', 'Çin Makao ÖİB', 'Macao SAR China', 'Макао (САР)', 100),
  ('MP', 'Kuzey Mariana Adaları', 'Northern Mariana Islands', 'Северные Марианские о-ва', 100),
  ('MQ', 'Martinik', 'Martinique', 'Мартиника', 100),
  ('MR', 'Moritanya', 'Mauritania', 'Мавритания', 100),
  ('MS', 'Montserrat', 'Montserrat', 'Монтсеррат', 100),
  ('MT', 'Malta', 'Malta', 'Мальта', 100),
  ('MU', 'Mauritius', 'Mauritius', 'Маврикий', 100),
  ('MV', 'Maldivler', 'Maldives', 'Мальдивы', 100),
  ('MW', 'Malavi', 'Malawi', 'Малави', 100),
  ('MX', 'Meksika', 'Mexico', 'Мексика', 100),
  ('MY', 'Malezya', 'Malaysia', 'Малайзия', 100),
  ('MZ', 'Mozambik', 'Mozambique', 'Мозамбик', 100),
  ('NA', 'Namibya', 'Namibia', 'Намибия', 100),
  ('NC', 'Yeni Kaledonya', 'New Caledonia', 'Новая Каледония', 100),
  ('NE', 'Nijer', 'Niger', 'Нигер', 100),
  ('NF', 'Norfolk Adası', 'Norfolk Island', 'о-в Норфолк', 100),
  ('NG', 'Nijerya', 'Nigeria', 'Нигерия', 100),
  ('NI', 'Nikaragua', 'Nicaragua', 'Никарагуа', 100),
  ('NL', 'Hollanda', 'Netherlands', 'Нидерланды', 100),
  ('NO', 'Norveç', 'Norway', 'Норвегия', 100),
  ('NP', 'Nepal', 'Nepal', 'Непал', 100),
  ('NR', 'Nauru', 'Nauru', 'Науру', 100),
  ('NU', 'Niue', 'Niue', 'Ниуэ', 100),
  ('NZ', 'Yeni Zelanda', 'New Zealand', 'Новая Зеландия', 100),
  ('OM', 'Umman', 'Oman', 'Оман', 100),
  ('PA', 'Panama', 'Panama', 'Панама', 100),
  ('PE', 'Peru', 'Peru', 'Перу', 100),
  ('PF', 'Fransız Polinezyası', 'French Polynesia', 'Французская Полинезия', 100),
  ('PG', 'Papua Yeni Gine', 'Papua New Guinea', 'Папуа — Новая Гвинея', 100),
  ('PH', 'Filipinler', 'Philippines', 'Филиппины', 100),
  ('PK', 'Pakistan', 'Pakistan', 'Пакистан', 100),
  ('PL', 'Polonya', 'Poland', 'Польша', 100),
  ('PM', 'Saint Pierre ve Miquelon', 'St. Pierre & Miquelon', 'Сен-Пьер и Микелон', 100),
  ('PN', 'Pitcairn Adaları', 'Pitcairn Islands', 'о-ва Питкэрн', 100),
  ('PR', 'Porto Riko', 'Puerto Rico', 'Пуэрто-Рико', 100),
  ('PS', 'Filistin Bölgeleri', 'Palestinian Territories', 'Палестинские территории', 100),
  ('PT', 'Portekiz', 'Portugal', 'Португалия', 100),
  ('PW', 'Palau', 'Palau', 'Палау', 100),
  ('PY', 'Paraguay', 'Paraguay', 'Парагвай', 100),
  ('QA', 'Katar', 'Qatar', 'Катар', 100),
  ('RE', 'Reunion', 'Réunion', 'Реюньон', 100),
  ('RO', 'Romanya', 'Romania', 'Румыния', 100),
  ('RS', 'Sırbistan', 'Serbia', 'Сербия', 100),
  ('RU', 'Rusya', 'Russia', 'Россия', 100),
  ('RW', 'Ruanda', 'Rwanda', 'Руанда', 100),
  ('SA', 'Suudi Arabistan', 'Saudi Arabia', 'Саудовская Аравия', 100),
  ('SB', 'Solomon Adaları', 'Solomon Islands', 'Соломоновы Острова', 100),
  ('SC', 'Seyşeller', 'Seychelles', 'Сейшельские Острова', 100),
  ('SD', 'Sudan', 'Sudan', 'Судан', 100),
  ('SE', 'İsveç', 'Sweden', 'Швеция', 100),
  ('SG', 'Singapur', 'Singapore', 'Сингапур', 100),
  ('SH', 'Saint Helena', 'St. Helena', 'о-в Св. Елены', 100),
  ('SI', 'Slovenya', 'Slovenia', 'Словения', 100),
  ('SJ', 'Svalbard ve Jan Mayen', 'Svalbard & Jan Mayen', 'Шпицберген и Ян-Майен', 100),
  ('SK', 'Slovakya', 'Slovakia', 'Словакия', 100),
  ('SL', 'Sierra Leone', 'Sierra Leone', 'Сьерра-Леоне', 100),
  ('SM', 'San Marino', 'San Marino', 'Сан-Марино', 100),
  ('SN', 'Senegal', 'Senegal', 'Сенегал', 100),
  ('SO', 'Somali', 'Somalia', 'Сомали', 100),
  ('SR', 'Surinam', 'Suriname', 'Суринам', 100),
  ('SS', 'Güney Sudan', 'South Sudan', 'Южный Судан', 100),
  ('ST', 'Sao Tome ve Principe', 'São Tomé & Príncipe', 'Сан-Томе и Принсипи', 100),
  ('SV', 'El Salvador', 'El Salvador', 'Сальвадор', 100),
  ('SX', 'Sint Maarten', 'Sint Maarten', 'Синт-Мартен', 100),
  ('SY', 'Suriye', 'Syria', 'Сирия', 100),
  ('SZ', 'Esvatini', 'Eswatini', 'Эсватини', 100),
  ('TC', 'Turks ve Caicos Adaları', 'Turks & Caicos Islands', 'о-ва Тёркс и Кайкос', 100),
  ('TD', 'Çad', 'Chad', 'Чад', 100),
  ('TF', 'Fransız Güney Toprakları', 'French Southern Territories', 'Французские Южные территории', 100),
  ('TG', 'Togo', 'Togo', 'Того', 100),
  ('TH', 'Tayland', 'Thailand', 'Таиланд', 100),
  ('TJ', 'Tacikistan', 'Tajikistan', 'Таджикистан', 100),
  ('TK', 'Tokelau', 'Tokelau', 'Токелау', 100),
  ('TL', 'Timor-Leste', 'Timor-Leste', 'Восточный Тимор', 100),
  ('TM', 'Türkmenistan', 'Turkmenistan', 'Туркменистан', 100),
  ('TN', 'Tunus', 'Tunisia', 'Тунис', 100),
  ('TO', 'Tonga', 'Tonga', 'Тонга', 100),
  ('TR', 'Türkiye', 'Turkey', 'Турция', 1),
  ('TT', 'Trinidad ve Tobago', 'Trinidad & Tobago', 'Тринидад и Тобаго', 100),
  ('TV', 'Tuvalu', 'Tuvalu', 'Тувалу', 100),
  ('TW', 'Tayvan', 'Taiwan', 'Тайвань', 100),
  ('TZ', 'Tanzanya', 'Tanzania', 'Танзания', 100),
  ('UA', 'Ukrayna', 'Ukraine', 'Украина', 100),
  ('UG', 'Uganda', 'Uganda', 'Уганда', 100),
  ('UM', 'ABD Küçük Harici Adaları', 'U.S. Outlying Islands', 'Внешние малые о-ва (США)', 100),
  ('US', 'Amerika Birleşik Devletleri', 'United States', 'Соединенные Штаты', 100),
  ('UY', 'Uruguay', 'Uruguay', 'Уругвай', 100),
  ('UZ', 'Özbekistan', 'Uzbekistan', 'Узбекистан', 100),
  ('VA', 'Vatikan', 'Vatican City', 'Ватикан', 100),
  ('VC', 'Saint Vincent ve Grenadinler', 'St. Vincent & Grenadines', 'Сент-Винсент и Гренадины', 100),
  ('VE', 'Venezuela', 'Venezuela', 'Венесуэла', 100),
  ('VG', 'Britanya Virjin Adaları', 'British Virgin Islands', 'Виргинские о-ва (Великобритания)', 100),
  ('VI', 'ABD Virjin Adaları', 'U.S. Virgin Islands', 'Виргинские о-ва (США)', 100),
  ('VN', 'Vietnam', 'Vietnam', 'Вьетнам', 100),
  ('VU', 'Vanuatu', 'Vanuatu', 'Вануату', 100),
  ('WF', 'Wallis ve Futuna', 'Wallis & Futuna', 'Уоллис и Футуна', 100),
  ('WS', 'Samoa', 'Samoa', 'Самоа', 100),
  ('YE', 'Yemen', 'Yemen', 'Йемен', 100),
  ('YT', 'Mayotte', 'Mayotte', 'Майотта', 100),
  ('ZA', 'Güney Afrika', 'South Africa', 'Южно-Африканская Республика', 100),
  ('ZM', 'Zambiya', 'Zambia', 'Замбия', 100),
  ('ZW', 'Zimbabve', 'Zimbabwe', 'Зимбабве', 100)
on conflict (code) do update set
  name_tr = excluded.name_tr,
  name_en = excluded.name_en,
  name_ru = excluded.name_ru,
  sort_order = excluded.sort_order;

-- ---------- İller ----------
insert into regions (country_code, parent_id, level, code, name) values
  ('TR', null, 1, '01', 'Adana'),
  ('TR', null, 1, '02', 'Adıyaman'),
  ('TR', null, 1, '03', 'Afyonkarahisar'),
  ('TR', null, 1, '04', 'Ağrı'),
  ('TR', null, 1, '05', 'Amasya'),
  ('TR', null, 1, '06', 'Ankara'),
  ('TR', null, 1, '07', 'Antalya'),
  ('TR', null, 1, '08', 'Artvin'),
  ('TR', null, 1, '09', 'Aydın'),
  ('TR', null, 1, '10', 'Balıkesir'),
  ('TR', null, 1, '11', 'Bilecik'),
  ('TR', null, 1, '12', 'Bingöl'),
  ('TR', null, 1, '13', 'Bitlis'),
  ('TR', null, 1, '14', 'Bolu'),
  ('TR', null, 1, '15', 'Burdur'),
  ('TR', null, 1, '16', 'Bursa'),
  ('TR', null, 1, '17', 'Çanakkale'),
  ('TR', null, 1, '18', 'Çankırı'),
  ('TR', null, 1, '19', 'Çorum'),
  ('TR', null, 1, '20', 'Denizli'),
  ('TR', null, 1, '21', 'Diyarbakır'),
  ('TR', null, 1, '22', 'Edirne'),
  ('TR', null, 1, '23', 'Elazığ'),
  ('TR', null, 1, '24', 'Erzincan'),
  ('TR', null, 1, '25', 'Erzurum'),
  ('TR', null, 1, '26', 'Eskişehir'),
  ('TR', null, 1, '27', 'Gaziantep'),
  ('TR', null, 1, '28', 'Giresun'),
  ('TR', null, 1, '29', 'Gümüşhane'),
  ('TR', null, 1, '30', 'Hakkari'),
  ('TR', null, 1, '31', 'Hatay'),
  ('TR', null, 1, '32', 'Isparta'),
  ('TR', null, 1, '33', 'Mersin'),
  ('TR', null, 1, '34', 'İstanbul'),
  ('TR', null, 1, '35', 'İzmir'),
  ('TR', null, 1, '36', 'Kars'),
  ('TR', null, 1, '37', 'Kastamonu'),
  ('TR', null, 1, '38', 'Kayseri'),
  ('TR', null, 1, '39', 'Kırklareli'),
  ('TR', null, 1, '40', 'Kırşehir'),
  ('TR', null, 1, '41', 'Kocaeli'),
  ('TR', null, 1, '42', 'Konya'),
  ('TR', null, 1, '43', 'Kütahya'),
  ('TR', null, 1, '44', 'Malatya'),
  ('TR', null, 1, '45', 'Manisa'),
  ('TR', null, 1, '46', 'Kahramanmaraş'),
  ('TR', null, 1, '47', 'Mardin'),
  ('TR', null, 1, '48', 'Muğla'),
  ('TR', null, 1, '49', 'Muş'),
  ('TR', null, 1, '50', 'Nevşehir'),
  ('TR', null, 1, '51', 'Niğde'),
  ('TR', null, 1, '52', 'Ordu'),
  ('TR', null, 1, '53', 'Rize'),
  ('TR', null, 1, '54', 'Sakarya'),
  ('TR', null, 1, '55', 'Samsun'),
  ('TR', null, 1, '56', 'Siirt'),
  ('TR', null, 1, '57', 'Sinop'),
  ('TR', null, 1, '58', 'Sivas'),
  ('TR', null, 1, '59', 'Tekirdağ'),
  ('TR', null, 1, '60', 'Tokat'),
  ('TR', null, 1, '61', 'Trabzon'),
  ('TR', null, 1, '62', 'Tunceli'),
  ('TR', null, 1, '63', 'Şanlıurfa'),
  ('TR', null, 1, '64', 'Uşak'),
  ('TR', null, 1, '65', 'Van'),
  ('TR', null, 1, '66', 'Yozgat'),
  ('TR', null, 1, '67', 'Zonguldak'),
  ('TR', null, 1, '68', 'Aksaray'),
  ('TR', null, 1, '69', 'Bayburt'),
  ('TR', null, 1, '70', 'Karaman'),
  ('TR', null, 1, '71', 'Kırıkkale'),
  ('TR', null, 1, '72', 'Batman'),
  ('TR', null, 1, '73', 'Şırnak'),
  ('TR', null, 1, '74', 'Bartın'),
  ('TR', null, 1, '75', 'Ardahan'),
  ('TR', null, 1, '76', 'Iğdır'),
  ('TR', null, 1, '77', 'Yalova'),
  ('TR', null, 1, '78', 'Karabük'),
  ('TR', null, 1, '79', 'Kilis'),
  ('TR', null, 1, '80', 'Osmaniye'),
  ('TR', null, 1, '81', 'Düzce')
on conflict do nothing;

-- ---------- İlçeler ----------
-- İl kimlikleri üretimde farklı olacağı için plaka koduyla eşleştirilir.
insert into regions (country_code, parent_id, level, name)
select 'TR', p.id, 2, d.name
from (values
  ('01', 'Aladağ'),
  ('01', 'Ceyhan'),
  ('01', 'Feke'),
  ('01', 'Karaisalı'),
  ('01', 'Karataş'),
  ('01', 'Kozan'),
  ('01', 'Pozantı'),
  ('01', 'Saimbeyli'),
  ('01', 'Sarıçam'),
  ('01', 'Seyhan'),
  ('01', 'Tufanbeyli'),
  ('01', 'Yumurtalık'),
  ('01', 'Yüreğir'),
  ('01', 'Çukurova'),
  ('01', 'İmamoğlu'),
  ('02', 'Besni'),
  ('02', 'Gerger'),
  ('02', 'Gölbaşı'),
  ('02', 'Kahta'),
  ('02', 'Merkez'),
  ('02', 'Samsat'),
  ('02', 'Sincik'),
  ('02', 'Tut'),
  ('02', 'Çelikhan'),
  ('03', 'Bayat'),
  ('03', 'Başmakçı'),
  ('03', 'Bolvadin'),
  ('03', 'Dazkırı'),
  ('03', 'Dinar'),
  ('03', 'Emirdağ'),
  ('03', 'Evciler'),
  ('03', 'Hocalar'),
  ('03', 'Kızılören'),
  ('03', 'Merkez'),
  ('03', 'Sandıklı'),
  ('03', 'Sinanpaşa'),
  ('03', 'Sultandağı'),
  ('03', 'Çay'),
  ('03', 'Çobanlar'),
  ('03', 'İhsaniye'),
  ('03', 'İscehisar'),
  ('03', 'Şuhut'),
  ('04', 'Diyadin'),
  ('04', 'Doğubayazıt'),
  ('04', 'Eleşkirt'),
  ('04', 'Hamur'),
  ('04', 'Merkez'),
  ('04', 'Patnos'),
  ('04', 'Taşlıçay'),
  ('04', 'Tutak'),
  ('05', 'Göynücek'),
  ('05', 'Gümüşhacıköy'),
  ('05', 'Hamamözü'),
  ('05', 'Merkez'),
  ('05', 'Merzifon'),
  ('05', 'Suluova'),
  ('05', 'Taşova'),
  ('06', 'Akyurt'),
  ('06', 'Altındağ'),
  ('06', 'Ayaş'),
  ('06', 'Bala'),
  ('06', 'Beypazarı'),
  ('06', 'Elmadağ'),
  ('06', 'Etimesgut'),
  ('06', 'Evren'),
  ('06', 'Gölbaşı'),
  ('06', 'Güdül'),
  ('06', 'Haymana'),
  ('06', 'Kahramankazan'),
  ('06', 'Kalecik'),
  ('06', 'Keçiören'),
  ('06', 'Kızılcahamam'),
  ('06', 'Mamak'),
  ('06', 'Nallıhan'),
  ('06', 'Polatlı'),
  ('06', 'Pursaklar'),
  ('06', 'Sincan'),
  ('06', 'Yenimahalle'),
  ('06', 'Çamlıdere'),
  ('06', 'Çankaya'),
  ('06', 'Çubuk'),
  ('06', 'Şereflikoçhisar'),
  ('07', 'Akseki'),
  ('07', 'Aksu'),
  ('07', 'Alanya'),
  ('07', 'Demre'),
  ('07', 'Döşemealtı'),
  ('07', 'Elmalı'),
  ('07', 'Finike'),
  ('07', 'Gazipaşa'),
  ('07', 'Gündoğmuş'),
  ('07', 'Kaş'),
  ('07', 'Kemer'),
  ('07', 'Kepez'),
  ('07', 'Konyaaltı'),
  ('07', 'Korkuteli'),
  ('07', 'Kumluca'),
  ('07', 'Manavgat'),
  ('07', 'Muratpaşa'),
  ('07', 'Serik'),
  ('07', 'İbradı'),
  ('08', 'Ardanuç'),
  ('08', 'Arhavi'),
  ('08', 'Borçka'),
  ('08', 'Hopa'),
  ('08', 'Kemalpaşa'),
  ('08', 'Merkez'),
  ('08', 'Murgul'),
  ('08', 'Yusufeli'),
  ('08', 'Şavşat'),
  ('09', 'Bozdoğan'),
  ('09', 'Buharkent'),
  ('09', 'Didim'),
  ('09', 'Efeler'),
  ('09', 'Germencik'),
  ('09', 'Karacasu'),
  ('09', 'Karpuzlu'),
  ('09', 'Koçarlı'),
  ('09', 'Kuyucak'),
  ('09', 'Kuşadası'),
  ('09', 'Köşk'),
  ('09', 'Nazilli'),
  ('09', 'Sultanhisar'),
  ('09', 'Söke'),
  ('09', 'Yenipazar'),
  ('09', 'Çine'),
  ('09', 'İncirliova'),
  ('10', 'Altıeylül'),
  ('10', 'Ayvalık'),
  ('10', 'Balya'),
  ('10', 'Bandırma'),
  ('10', 'Bigadiç'),
  ('10', 'Burhaniye'),
  ('10', 'Dursunbey'),
  ('10', 'Edremit'),
  ('10', 'Erdek'),
  ('10', 'Gömeç'),
  ('10', 'Gönen'),
  ('10', 'Havran'),
  ('10', 'Karesi'),
  ('10', 'Kepsut'),
  ('10', 'Manyas'),
  ('10', 'Marmara'),
  ('10', 'Savaştepe'),
  ('10', 'Susurluk'),
  ('10', 'Sındırgı'),
  ('10', 'İvrindi'),
  ('11', 'Bozüyük'),
  ('11', 'Gölpazarı'),
  ('11', 'Merkez'),
  ('11', 'Osmaneli'),
  ('11', 'Pazaryeri'),
  ('11', 'Söğüt'),
  ('11', 'Yenipazar'),
  ('11', 'İnhisar'),
  ('12', 'Adaklı'),
  ('12', 'Genç'),
  ('12', 'Karlıova'),
  ('12', 'Kiğı'),
  ('12', 'Merkez'),
  ('12', 'Solhan'),
  ('12', 'Yayladere'),
  ('12', 'Yedisu'),
  ('13', 'Adilcevaz'),
  ('13', 'Ahlat'),
  ('13', 'Güroymak'),
  ('13', 'Hizan'),
  ('13', 'Merkez'),
  ('13', 'Mutki'),
  ('13', 'Tatvan'),
  ('14', 'Dörtdivan'),
  ('14', 'Gerede'),
  ('14', 'Göynük'),
  ('14', 'Kıbrıscık'),
  ('14', 'Mengen'),
  ('14', 'Merkez'),
  ('14', 'Mudurnu'),
  ('14', 'Seben'),
  ('14', 'Yeniçağa'),
  ('15', 'Altınyayla'),
  ('15', 'Ağlasun'),
  ('15', 'Bucak'),
  ('15', 'Gölhisar'),
  ('15', 'Karamanlı'),
  ('15', 'Kemer'),
  ('15', 'Merkez'),
  ('15', 'Tefenni'),
  ('15', 'Yeşilova'),
  ('15', 'Çavdır'),
  ('15', 'Çeltikçi'),
  ('16', 'Büyükorhan'),
  ('16', 'Gemlik'),
  ('16', 'Gürsu'),
  ('16', 'Harmancık'),
  ('16', 'Karacabey'),
  ('16', 'Keles'),
  ('16', 'Kestel'),
  ('16', 'Mudanya'),
  ('16', 'Mustafakemalpaşa'),
  ('16', 'Nilüfer'),
  ('16', 'Orhaneli'),
  ('16', 'Orhangazi'),
  ('16', 'Osmangazi'),
  ('16', 'Yenişehir'),
  ('16', 'Yıldırım'),
  ('16', 'İnegöl'),
  ('16', 'İznik'),
  ('17', 'Ayvacık'),
  ('17', 'Bayramiç'),
  ('17', 'Biga'),
  ('17', 'Bozcaada'),
  ('17', 'Eceabat'),
  ('17', 'Ezine'),
  ('17', 'Gelibolu'),
  ('17', 'Gökçeada'),
  ('17', 'Lapseki'),
  ('17', 'Merkez'),
  ('17', 'Yenice'),
  ('17', 'Çan'),
  ('18', 'Atkaracalar'),
  ('18', 'Bayramören'),
  ('18', 'Eldivan'),
  ('18', 'Ilgaz'),
  ('18', 'Korgun'),
  ('18', 'Kurşunlu'),
  ('18', 'Kızılırmak'),
  ('18', 'Merkez'),
  ('18', 'Orta'),
  ('18', 'Yapraklı'),
  ('18', 'Çerkeş'),
  ('18', 'Şabanözü'),
  ('19', 'Alaca'),
  ('19', 'Bayat'),
  ('19', 'Boğazkale'),
  ('19', 'Dodurga'),
  ('19', 'Kargı'),
  ('19', 'Laçin'),
  ('19', 'Mecitözü'),
  ('19', 'Merkez'),
  ('19', 'Ortaköy'),
  ('19', 'Osmancık'),
  ('19', 'Oğuzlar'),
  ('19', 'Sungurlu'),
  ('19', 'Uğurludağ'),
  ('19', 'İskilip'),
  ('20', 'Acıpayam'),
  ('20', 'Babadağ'),
  ('20', 'Baklan'),
  ('20', 'Bekilli'),
  ('20', 'Beyağaç'),
  ('20', 'Bozkurt'),
  ('20', 'Buldan'),
  ('20', 'Güney'),
  ('20', 'Honaz'),
  ('20', 'Kale'),
  ('20', 'Merkezefendi'),
  ('20', 'Pamukkale'),
  ('20', 'Sarayköy'),
  ('20', 'Serinhisar'),
  ('20', 'Tavas'),
  ('20', 'Çal'),
  ('20', 'Çameli'),
  ('20', 'Çardak'),
  ('20', 'Çivril'),
  ('21', 'Bağlar'),
  ('21', 'Bismil'),
  ('21', 'Dicle'),
  ('21', 'Ergani'),
  ('21', 'Eğil'),
  ('21', 'Hani'),
  ('21', 'Hazro'),
  ('21', 'Kayapınar'),
  ('21', 'Kocaköy'),
  ('21', 'Kulp'),
  ('21', 'Lice'),
  ('21', 'Silvan'),
  ('21', 'Sur'),
  ('21', 'Yenişehir'),
  ('21', 'Çermik'),
  ('21', 'Çüngüş'),
  ('21', 'Çınar'),
  ('22', 'Enez'),
  ('22', 'Havsa'),
  ('22', 'Keşan'),
  ('22', 'Lalapaşa'),
  ('22', 'Meriç'),
  ('22', 'Merkez'),
  ('22', 'Süloğlu'),
  ('22', 'Uzunköprü'),
  ('22', 'İpsala'),
  ('23', 'Alacakaya'),
  ('23', 'Arıcak'),
  ('23', 'Ağın'),
  ('23', 'Baskil'),
  ('23', 'Karakoçan'),
  ('23', 'Keban'),
  ('23', 'Kovancılar'),
  ('23', 'Maden'),
  ('23', 'Merkez'),
  ('23', 'Palu'),
  ('23', 'Sivrice'),
  ('24', 'Kemah'),
  ('24', 'Kemaliye'),
  ('24', 'Merkez'),
  ('24', 'Otlukbeli'),
  ('24', 'Refahiye'),
  ('24', 'Tercan'),
  ('24', 'Çayırlı'),
  ('24', 'Üzümlü'),
  ('24', 'İliç'),
  ('25', 'Aziziye'),
  ('25', 'Aşkale'),
  ('25', 'Horasan'),
  ('25', 'Hınıs'),
  ('25', 'Karayazı'),
  ('25', 'Karaçoban'),
  ('25', 'Köprüköy'),
  ('25', 'Narman'),
  ('25', 'Oltu'),
  ('25', 'Olur'),
  ('25', 'Palandöken'),
  ('25', 'Pasinler'),
  ('25', 'Pazaryolu'),
  ('25', 'Tekman'),
  ('25', 'Tortum'),
  ('25', 'Uzundere'),
  ('25', 'Yakutiye'),
  ('25', 'Çat'),
  ('25', 'İspir'),
  ('25', 'Şenkaya'),
  ('26', 'Alpu'),
  ('26', 'Beylikova'),
  ('26', 'Günyüzü'),
  ('26', 'Han'),
  ('26', 'Mahmudiye'),
  ('26', 'Mihalgazi'),
  ('26', 'Mihalıççık'),
  ('26', 'Odunpazarı'),
  ('26', 'Sarıcakaya'),
  ('26', 'Seyitgazi'),
  ('26', 'Sivrihisar'),
  ('26', 'Tepebaşı'),
  ('26', 'Çifteler'),
  ('26', 'İnönü'),
  ('27', 'Araban'),
  ('27', 'Karkamış'),
  ('27', 'Nizip'),
  ('27', 'Nurdağı'),
  ('27', 'Oğuzeli'),
  ('27', 'Yavuzeli'),
  ('27', 'İslahiye'),
  ('27', 'Şahinbey'),
  ('27', 'Şehitkamil'),
  ('28', 'Alucra'),
  ('28', 'Bulancak'),
  ('28', 'Dereli'),
  ('28', 'Doğankent'),
  ('28', 'Espiye'),
  ('28', 'Eynesil'),
  ('28', 'Görele'),
  ('28', 'Güce'),
  ('28', 'Keşap'),
  ('28', 'Merkez'),
  ('28', 'Piraziz'),
  ('28', 'Tirebolu'),
  ('28', 'Yağlıdere'),
  ('28', 'Çamoluk'),
  ('28', 'Çanakçı'),
  ('28', 'Şebinkarahisar'),
  ('29', 'Kelkit'),
  ('29', 'Köse'),
  ('29', 'Kürtün'),
  ('29', 'Merkez'),
  ('29', 'Torul'),
  ('29', 'Şiran'),
  ('30', 'Derecik'),
  ('30', 'Merkez'),
  ('30', 'Yüksekova'),
  ('30', 'Çukurca'),
  ('30', 'Şemdinli'),
  ('31', 'Altınözü'),
  ('31', 'Antakya'),
  ('31', 'Arsuz'),
  ('31', 'Belen'),
  ('31', 'Defne'),
  ('31', 'Dörtyol'),
  ('31', 'Erzin'),
  ('31', 'Hassa'),
  ('31', 'Kumlu'),
  ('31', 'Kırıkhan'),
  ('31', 'Payas'),
  ('31', 'Reyhanlı'),
  ('31', 'Samandağ'),
  ('31', 'Yayladağı'),
  ('31', 'İskenderun'),
  ('32', 'Aksu'),
  ('32', 'Atabey'),
  ('32', 'Eğirdir'),
  ('32', 'Gelendost'),
  ('32', 'Gönen'),
  ('32', 'Keçiborlu'),
  ('32', 'Merkez'),
  ('32', 'Senirkent'),
  ('32', 'Sütçüler'),
  ('32', 'Uluborlu'),
  ('32', 'Yalvaç'),
  ('32', 'Yenişarbademli'),
  ('32', 'Şarkikaraağaç'),
  ('33', 'Akdeniz'),
  ('33', 'Anamur'),
  ('33', 'Aydıncık'),
  ('33', 'Bozyazı'),
  ('33', 'Erdemli'),
  ('33', 'Gülnar'),
  ('33', 'Mezitli'),
  ('33', 'Mut'),
  ('33', 'Silifke'),
  ('33', 'Tarsus'),
  ('33', 'Toroslar'),
  ('33', 'Yenişehir'),
  ('33', 'Çamlıyayla'),
  ('34', 'Adalar'),
  ('34', 'Arnavutköy'),
  ('34', 'Ataşehir'),
  ('34', 'Avcılar'),
  ('34', 'Bahçelievler'),
  ('34', 'Bakırköy'),
  ('34', 'Bayrampaşa'),
  ('34', 'Bağcılar'),
  ('34', 'Başakşehir'),
  ('34', 'Beykoz'),
  ('34', 'Beylikdüzü'),
  ('34', 'Beyoğlu'),
  ('34', 'Beşiktaş'),
  ('34', 'Büyükçekmece'),
  ('34', 'Esenler'),
  ('34', 'Esenyurt'),
  ('34', 'Eyüpsultan'),
  ('34', 'Fatih'),
  ('34', 'Gaziosmanpaşa'),
  ('34', 'Güngören'),
  ('34', 'Kadıköy'),
  ('34', 'Kartal'),
  ('34', 'Kağıthane'),
  ('34', 'Küçükçekmece'),
  ('34', 'Maltepe'),
  ('34', 'Pendik'),
  ('34', 'Sancaktepe'),
  ('34', 'Sarıyer'),
  ('34', 'Silivri'),
  ('34', 'Sultanbeyli'),
  ('34', 'Sultangazi'),
  ('34', 'Tuzla'),
  ('34', 'Zeytinburnu'),
  ('34', 'Çatalca'),
  ('34', 'Çekmeköy'),
  ('34', 'Ümraniye'),
  ('34', 'Üsküdar'),
  ('34', 'Şile'),
  ('34', 'Şişli'),
  ('35', 'Aliağa'),
  ('35', 'Balçova'),
  ('35', 'Bayraklı'),
  ('35', 'Bayındır'),
  ('35', 'Bergama'),
  ('35', 'Beydağ'),
  ('35', 'Bornova'),
  ('35', 'Buca'),
  ('35', 'Dikili'),
  ('35', 'Foça'),
  ('35', 'Gaziemir'),
  ('35', 'Güzelbahçe'),
  ('35', 'Karabağlar'),
  ('35', 'Karaburun'),
  ('35', 'Karşıyaka'),
  ('35', 'Kemalpaşa'),
  ('35', 'Kiraz'),
  ('35', 'Konak'),
  ('35', 'Kınık'),
  ('35', 'Menderes'),
  ('35', 'Menemen'),
  ('35', 'Narlıdere'),
  ('35', 'Seferihisar'),
  ('35', 'Selçuk'),
  ('35', 'Tire'),
  ('35', 'Torbalı'),
  ('35', 'Urla'),
  ('35', 'Çeşme'),
  ('35', 'Çiğli'),
  ('35', 'Ödemiş'),
  ('36', 'Akyaka'),
  ('36', 'Arpaçay'),
  ('36', 'Digor'),
  ('36', 'Kağızman'),
  ('36', 'Merkez'),
  ('36', 'Sarıkamış'),
  ('36', 'Selim'),
  ('36', 'Susuz'),
  ('37', 'Abana'),
  ('37', 'Araç'),
  ('37', 'Azdavay'),
  ('37', 'Ağlı'),
  ('37', 'Bozkurt'),
  ('37', 'Cide'),
  ('37', 'Daday'),
  ('37', 'Devrekani'),
  ('37', 'Doğanyurt'),
  ('37', 'Hanönü'),
  ('37', 'Küre'),
  ('37', 'Merkez'),
  ('37', 'Pınarbaşı'),
  ('37', 'Seydiler'),
  ('37', 'Taşköprü'),
  ('37', 'Tosya'),
  ('37', 'Çatalzeytin'),
  ('37', 'İhsangazi'),
  ('37', 'İnebolu'),
  ('37', 'Şenpazar'),
  ('38', 'Akkışla'),
  ('38', 'Bünyan'),
  ('38', 'Develi'),
  ('38', 'Felahiye'),
  ('38', 'Hacılar'),
  ('38', 'Kocasinan'),
  ('38', 'Melikgazi'),
  ('38', 'Pınarbaşı'),
  ('38', 'Sarıoğlan'),
  ('38', 'Sarız'),
  ('38', 'Talas'),
  ('38', 'Tomarza'),
  ('38', 'Yahyalı'),
  ('38', 'Yeşilhisar'),
  ('38', 'Özvatan'),
  ('38', 'İncesu'),
  ('39', 'Babaeski'),
  ('39', 'Demirköy'),
  ('39', 'Kofçaz'),
  ('39', 'Lüleburgaz'),
  ('39', 'Merkez'),
  ('39', 'Pehlivanköy'),
  ('39', 'Pınarhisar'),
  ('39', 'Vize'),
  ('40', 'Akpınar'),
  ('40', 'Akçakent'),
  ('40', 'Boztepe'),
  ('40', 'Kaman'),
  ('40', 'Merkez'),
  ('40', 'Mucur'),
  ('40', 'Çiçekdağı'),
  ('41', 'Başiskele'),
  ('41', 'Darıca'),
  ('41', 'Derince'),
  ('41', 'Dilovası'),
  ('41', 'Gebze'),
  ('41', 'Gölcük'),
  ('41', 'Kandıra'),
  ('41', 'Karamürsel'),
  ('41', 'Kartepe'),
  ('41', 'Körfez'),
  ('41', 'Çayırova'),
  ('41', 'İzmit'),
  ('42', 'Ahırlı'),
  ('42', 'Akören'),
  ('42', 'Akşehir'),
  ('42', 'Altınekin'),
  ('42', 'Beyşehir'),
  ('42', 'Bozkır'),
  ('42', 'Cihanbeyli'),
  ('42', 'Derbent'),
  ('42', 'Derebucak'),
  ('42', 'Doğanhisar'),
  ('42', 'Emirgazi'),
  ('42', 'Ereğli'),
  ('42', 'Güneysınır'),
  ('42', 'Hadim'),
  ('42', 'Halkapınar'),
  ('42', 'Hüyük'),
  ('42', 'Ilgın'),
  ('42', 'Kadınhanı'),
  ('42', 'Karapınar'),
  ('42', 'Karatay'),
  ('42', 'Kulu'),
  ('42', 'Meram'),
  ('42', 'Sarayönü'),
  ('42', 'Selçuklu'),
  ('42', 'Seydişehir'),
  ('42', 'Taşkent'),
  ('42', 'Tuzlukçu'),
  ('42', 'Yalıhüyük'),
  ('42', 'Yunak'),
  ('42', 'Çeltik'),
  ('42', 'Çumra'),
  ('43', 'Altıntaş'),
  ('43', 'Aslanapa'),
  ('43', 'Domaniç'),
  ('43', 'Dumlupınar'),
  ('43', 'Emet'),
  ('43', 'Gediz'),
  ('43', 'Hisarcık'),
  ('43', 'Merkez'),
  ('43', 'Pazarlar'),
  ('43', 'Simav'),
  ('43', 'Tavşanlı'),
  ('43', 'Çavdarhisar'),
  ('43', 'Şaphane'),
  ('44', 'Akçadağ'),
  ('44', 'Arapgir'),
  ('44', 'Arguvan'),
  ('44', 'Battalgazi'),
  ('44', 'Darende'),
  ('44', 'Doğanyol'),
  ('44', 'Doğanşehir'),
  ('44', 'Hekimhan'),
  ('44', 'Kale'),
  ('44', 'Kuluncak'),
  ('44', 'Pütürge'),
  ('44', 'Yazıhan'),
  ('44', 'Yeşilyurt'),
  ('45', 'Ahmetli'),
  ('45', 'Akhisar'),
  ('45', 'Alaşehir'),
  ('45', 'Demirci'),
  ('45', 'Gölmarmara'),
  ('45', 'Gördes'),
  ('45', 'Kula'),
  ('45', 'Köprübaşı'),
  ('45', 'Kırkağaç'),
  ('45', 'Salihli'),
  ('45', 'Saruhanlı'),
  ('45', 'Sarıgöl'),
  ('45', 'Selendi'),
  ('45', 'Soma'),
  ('45', 'Turgutlu'),
  ('45', 'Yunusemre'),
  ('45', 'Şehzadeler'),
  ('46', 'Afşin'),
  ('46', 'Andırın'),
  ('46', 'Dulkadiroğlu'),
  ('46', 'Ekinözü'),
  ('46', 'Elbistan'),
  ('46', 'Göksun'),
  ('46', 'Nurhak'),
  ('46', 'Onikişubat'),
  ('46', 'Pazarcık'),
  ('46', 'Türkoğlu'),
  ('46', 'Çağlayancerit'),
  ('47', 'Artuklu'),
  ('47', 'Dargeçit'),
  ('47', 'Derik'),
  ('47', 'Kızıltepe'),
  ('47', 'Mazıdağı'),
  ('47', 'Midyat'),
  ('47', 'Nusaybin'),
  ('47', 'Savur'),
  ('47', 'Yeşilli'),
  ('47', 'Ömerli'),
  ('48', 'Bodrum'),
  ('48', 'Dalaman'),
  ('48', 'Datça'),
  ('48', 'Fethiye'),
  ('48', 'Kavaklıdere'),
  ('48', 'Köyceğiz'),
  ('48', 'Marmaris'),
  ('48', 'Menteşe'),
  ('48', 'Milas'),
  ('48', 'Ortaca'),
  ('48', 'Seydikemer'),
  ('48', 'Ula'),
  ('48', 'Yatağan'),
  ('49', 'Bulanık'),
  ('49', 'Hasköy'),
  ('49', 'Korkut'),
  ('49', 'Malazgirt'),
  ('49', 'Merkez'),
  ('49', 'Varto'),
  ('50', 'Acıgöl'),
  ('50', 'Avanos'),
  ('50', 'Derinkuyu'),
  ('50', 'Gülşehir'),
  ('50', 'Hacıbektaş'),
  ('50', 'Kozaklı'),
  ('50', 'Merkez'),
  ('50', 'Ürgüp'),
  ('51', 'Altunhisar'),
  ('51', 'Bor'),
  ('51', 'Merkez'),
  ('51', 'Ulukışla'),
  ('51', 'Çamardı'),
  ('51', 'Çiftlik'),
  ('52', 'Akkuş'),
  ('52', 'Altınordu'),
  ('52', 'Aybastı'),
  ('52', 'Fatsa'),
  ('52', 'Gölköy'),
  ('52', 'Gülyalı'),
  ('52', 'Gürgentepe'),
  ('52', 'Kabadüz'),
  ('52', 'Kabataş'),
  ('52', 'Korgan'),
  ('52', 'Kumru'),
  ('52', 'Mesudiye'),
  ('52', 'Perşembe'),
  ('52', 'Ulubey'),
  ('52', 'Çamaş'),
  ('52', 'Çatalpınar'),
  ('52', 'Çaybaşı'),
  ('52', 'Ünye'),
  ('52', 'İkizce'),
  ('53', 'Ardeşen'),
  ('53', 'Derepazarı'),
  ('53', 'Fındıklı'),
  ('53', 'Güneysu'),
  ('53', 'Hemşin'),
  ('53', 'Kalkandere'),
  ('53', 'Merkez'),
  ('53', 'Pazar'),
  ('53', 'Çamlıhemşin'),
  ('53', 'Çayeli'),
  ('53', 'İkizdere'),
  ('53', 'İyidere'),
  ('54', 'Adapazarı'),
  ('54', 'Akyazı'),
  ('54', 'Arifiye'),
  ('54', 'Erenler'),
  ('54', 'Ferizli'),
  ('54', 'Geyve'),
  ('54', 'Hendek'),
  ('54', 'Karapürçek'),
  ('54', 'Karasu'),
  ('54', 'Kaynarca'),
  ('54', 'Kocaali'),
  ('54', 'Pamukova'),
  ('54', 'Sapanca'),
  ('54', 'Serdivan'),
  ('54', 'Söğütlü'),
  ('54', 'Taraklı'),
  ('55', '19 Mayıs'),
  ('55', 'Alaçam'),
  ('55', 'Asarcık'),
  ('55', 'Atakum'),
  ('55', 'Ayvacık'),
  ('55', 'Bafra'),
  ('55', 'Canik'),
  ('55', 'Havza'),
  ('55', 'Kavak'),
  ('55', 'Ladik'),
  ('55', 'Salıpazarı'),
  ('55', 'Tekkeköy'),
  ('55', 'Terme'),
  ('55', 'Vezirköprü'),
  ('55', 'Yakakent'),
  ('55', 'Çarşamba'),
  ('55', 'İlkadım'),
  ('56', 'Baykan'),
  ('56', 'Eruh'),
  ('56', 'Kurtalan'),
  ('56', 'Merkez'),
  ('56', 'Pervari'),
  ('56', 'Tillo'),
  ('56', 'Şirvan'),
  ('57', 'Ayancık'),
  ('57', 'Boyabat'),
  ('57', 'Dikmen'),
  ('57', 'Durağan'),
  ('57', 'Erfelek'),
  ('57', 'Gerze'),
  ('57', 'Merkez'),
  ('57', 'Saraydüzü'),
  ('57', 'Türkeli'),
  ('58', 'Akıncılar'),
  ('58', 'Altınyayla'),
  ('58', 'Divriği'),
  ('58', 'Doğanşar'),
  ('58', 'Gemerek'),
  ('58', 'Gölova'),
  ('58', 'Gürün'),
  ('58', 'Hafik'),
  ('58', 'Kangal'),
  ('58', 'Koyulhisar'),
  ('58', 'Merkez'),
  ('58', 'Suşehri'),
  ('58', 'Ulaş'),
  ('58', 'Yıldızeli'),
  ('58', 'Zara'),
  ('58', 'İmranlı'),
  ('58', 'Şarkışla'),
  ('59', 'Ergene'),
  ('59', 'Hayrabolu'),
  ('59', 'Kapaklı'),
  ('59', 'Malkara'),
  ('59', 'Marmaraereğlisi'),
  ('59', 'Muratlı'),
  ('59', 'Saray'),
  ('59', 'Süleymanpaşa'),
  ('59', 'Çerkezköy'),
  ('59', 'Çorlu'),
  ('59', 'Şarköy'),
  ('60', 'Almus'),
  ('60', 'Artova'),
  ('60', 'Başçiftlik'),
  ('60', 'Erbaa'),
  ('60', 'Merkez'),
  ('60', 'Niksar'),
  ('60', 'Pazar'),
  ('60', 'Reşadiye'),
  ('60', 'Sulusaray'),
  ('60', 'Turhal'),
  ('60', 'Yeşilyurt'),
  ('60', 'Zile'),
  ('61', 'Akçaabat'),
  ('61', 'Araklı'),
  ('61', 'Arsin'),
  ('61', 'Beşikdüzü'),
  ('61', 'Dernekpazarı'),
  ('61', 'Düzköy'),
  ('61', 'Hayrat'),
  ('61', 'Köprübaşı'),
  ('61', 'Maçka'),
  ('61', 'Of'),
  ('61', 'Ortahisar'),
  ('61', 'Sürmene'),
  ('61', 'Tonya'),
  ('61', 'Vakfıkebir'),
  ('61', 'Yomra'),
  ('61', 'Çarşıbaşı'),
  ('61', 'Çaykara'),
  ('61', 'Şalpazarı'),
  ('62', 'Hozat'),
  ('62', 'Mazgirt'),
  ('62', 'Merkez'),
  ('62', 'Nazımiye'),
  ('62', 'Ovacık'),
  ('62', 'Pertek'),
  ('62', 'Pülümür'),
  ('62', 'Çemişgezek'),
  ('63', 'Akçakale'),
  ('63', 'Birecik'),
  ('63', 'Bozova'),
  ('63', 'Ceylanpınar'),
  ('63', 'Eyyübiye'),
  ('63', 'Halfeti'),
  ('63', 'Haliliye'),
  ('63', 'Harran'),
  ('63', 'Hilvan'),
  ('63', 'Karaköprü'),
  ('63', 'Siverek'),
  ('63', 'Suruç'),
  ('63', 'Viranşehir'),
  ('64', 'Banaz'),
  ('64', 'Eşme'),
  ('64', 'Karahallı'),
  ('64', 'Merkez'),
  ('64', 'Sivaslı'),
  ('64', 'Ulubey'),
  ('65', 'Bahçesaray'),
  ('65', 'Başkale'),
  ('65', 'Edremit'),
  ('65', 'Erciş'),
  ('65', 'Gevaş'),
  ('65', 'Gürpınar'),
  ('65', 'Muradiye'),
  ('65', 'Saray'),
  ('65', 'Tuşba'),
  ('65', 'Çaldıran'),
  ('65', 'Çatak'),
  ('65', 'Özalp'),
  ('65', 'İpekyolu'),
  ('66', 'Akdağmadeni'),
  ('66', 'Aydıncık'),
  ('66', 'Boğazlıyan'),
  ('66', 'Kadışehri'),
  ('66', 'Merkez'),
  ('66', 'Saraykent'),
  ('66', 'Sarıkaya'),
  ('66', 'Sorgun'),
  ('66', 'Yenifakılı'),
  ('66', 'Yerköy'),
  ('66', 'Çandır'),
  ('66', 'Çayıralan'),
  ('66', 'Çekerek'),
  ('66', 'Şefaatli'),
  ('67', 'Alaplı'),
  ('67', 'Devrek'),
  ('67', 'Ereğli'),
  ('67', 'Gökçebey'),
  ('67', 'Kilimli'),
  ('67', 'Kozlu'),
  ('67', 'Merkez'),
  ('67', 'Çaycuma'),
  ('68', 'Ağaçören'),
  ('68', 'Eskil'),
  ('68', 'Gülağaç'),
  ('68', 'Güzelyurt'),
  ('68', 'Merkez'),
  ('68', 'Ortaköy'),
  ('68', 'Sarıyahşi'),
  ('68', 'Sultanhanı'),
  ('69', 'Aydıntepe'),
  ('69', 'Demirözü'),
  ('69', 'Merkez'),
  ('70', 'Ayrancı'),
  ('70', 'Başyayla'),
  ('70', 'Ermenek'),
  ('70', 'Kazımkarabekir'),
  ('70', 'Merkez'),
  ('70', 'Sarıveliler'),
  ('71', 'Bahşılı'),
  ('71', 'Balışeyh'),
  ('71', 'Delice'),
  ('71', 'Karakeçili'),
  ('71', 'Keskin'),
  ('71', 'Merkez'),
  ('71', 'Sulakyurt'),
  ('71', 'Yahşihan'),
  ('71', 'Çelebi'),
  ('72', 'Beşiri'),
  ('72', 'Gercüş'),
  ('72', 'Hasankeyf'),
  ('72', 'Kozluk'),
  ('72', 'Merkez'),
  ('72', 'Sason'),
  ('73', 'Beytüşşebap'),
  ('73', 'Cizre'),
  ('73', 'Güçlükonak'),
  ('73', 'Merkez'),
  ('73', 'Silopi'),
  ('73', 'Uludere'),
  ('73', 'İdil'),
  ('74', 'Amasra'),
  ('74', 'Kurucaşile'),
  ('74', 'Merkez'),
  ('74', 'Ulus'),
  ('75', 'Damal'),
  ('75', 'Göle'),
  ('75', 'Hanak'),
  ('75', 'Merkez'),
  ('75', 'Posof'),
  ('75', 'Çıldır'),
  ('76', 'Aralık'),
  ('76', 'Karakoyunlu'),
  ('76', 'Merkez'),
  ('76', 'Tuzluca'),
  ('77', 'Altınova'),
  ('77', 'Armutlu'),
  ('77', 'Merkez'),
  ('77', 'Termal'),
  ('77', 'Çiftlikköy'),
  ('77', 'Çınarcık'),
  ('78', 'Eflani'),
  ('78', 'Eskipazar'),
  ('78', 'Merkez'),
  ('78', 'Ovacık'),
  ('78', 'Safranbolu'),
  ('78', 'Yenice'),
  ('79', 'Elbeyli'),
  ('79', 'Merkez'),
  ('79', 'Musabeyli'),
  ('79', 'Polateli'),
  ('80', 'Bahçe'),
  ('80', 'Düziçi'),
  ('80', 'Hasanbeyli'),
  ('80', 'Kadirli'),
  ('80', 'Merkez'),
  ('80', 'Sumbas'),
  ('80', 'Toprakkale'),
  ('81', 'Akçakoca'),
  ('81', 'Cumayeri'),
  ('81', 'Gölyaka'),
  ('81', 'Gümüşova'),
  ('81', 'Kaynaşlı'),
  ('81', 'Merkez'),
  ('81', 'Yığılca'),
  ('81', 'Çilimli')
) as d(plate, name)
join regions p
  on p.country_code = 'TR' and p.level = 1 and p.code = d.plate
on conflict (country_code, level, parent_id, name) do nothing;
